camp prototype model
ecamp/ecamp3 pull request #1031
Opened 2021-02-28 13:06 UTC by pmattmann

Isseu: #834

- [x] backend
- [x] frontend

![UML](https://yuml.me/69fa7556.png)
[Edit](https://yuml.me/edit/69fa7556)

2021-02-28 21:33 UTC, pmattmann commented
Ich habe es wie folgt implementiert:

![UML](https://yuml.me/842a89f1.png)
[edit](https://yuml.me/edit/842a89f1)

**Category** und **Activity** leiten von **AbstractContentNodeOwner** ab.
**AbstractContentNodeOwner** zeigt auf das Root-Element vom **ContentNode**-Tree.
Jeder **ContentNode** zeigt auf dessen Owner (**AbstractContentNodeOwner**).
Jeder **ContentNode** zeigt auf dessen Parent **ContentNode**. Ausnahme ist das Root-Element, dieses hat keinen weiteren Parent.

Die Zeiger von **ContentNode** auf **AbstractContentNodeOwner** benötige ich, um das Interface **BelongsToCamp** implementieren zu können. Sprich, damit ich herausfinden kann, zu welchem **Camp** ein **ContentNode** gehört.

**_Mögliche Alternative:_**
Anstelle vom Zeiger **ContentNode -> AbstractContentNodeOwner** könnte man auch folgendes machen:
OneToOne-Beziehung zwischen **AbstractContentNodeOwner <-> ContentNode** kombiniert mit einem Root-ContentNode-Zeiger auf allen ContentNodes **ContentNode -> Root-ContentNode**.

![UML](https://yuml.me/b67386bb.png)
[edit](https://yuml.me/edit/b67386bb)

2021-03-03 08:11 UTC, manuelmeister commented
Für was habt ihr euch entschieden?

2021-03-03 10:59 UTC, carlobeltrame commented
Für die zweite Option, da dann der ContentNode-Baum unabhängiger vom jeweiligen Owner ist. Er ist immer noch nicht ganz unabhängig, da es für den Berechtigungs-Check nötig ist, vom ContentNode aus zum Camp zu finden. Also wird (noch) nix mit komplett unabhängigen, wiederverwendbaren ContentNode-Bäumen.

Wir haben noch kurz eine dritte, noch "extremere", noch stärker normalisierte Variante besprochen, nämlich gar keinen `root` Zeiger zu haben. Um von einem beliebigen ContentNode zur Activity zu kommen müsste man sich dann durch die Baum-Hierarchie (parent vom parent vom parent ...) nach oben hangeln, bis man an einem Root Node ankommt. Das gäbe zwar am wenigsten Duplikation (und somit am wenigsten Potenzial für inkonsistente Daten beim vielen Klonen das wir machen werden), aber wäre mühsamer auszuführen, da Doctrine dazu wohl bei einer Baumtiefe n auch n Datenbank-Queries absetzen würde. Und da dieser Permissions-Check voraussichtlich relativ oft vorkommt, haben wir uns für den Moment dagegen entschieden.

Ich bin der Meinung dass die gewählte Option im Moment ausreicht, und trotzdem noch flexibel zu migrieren ist, falls wir uns umentscheiden sollten.

2021-03-04 22:16 UTC, pmattmann commented
PR is ready to merge.

Enthalten:
- Umbau backend
- Anpassung frontend, so dass bestehender Code mit Backend funktioniert

Nicht enthalten:
- Frontend:
  - Category-Verwaltung
    - Bevorzugte ContentTypes wählen
    - ContentNode-Struktur erstellen
  - Activity
    - ContentNode-Struktur erstellen

Bevorzugte ContentTypes pro Category ist ein neues Feature -> eigener PR.
ContentNode-Struktur erstellen lässt sich erst implementierne, wenn wir den "SpaltenLayout-ContentType" haben.

Temporärer Effekt:
Jeder Block kann genau ein ContentNode haben (der RootNode).

2021-03-05 15:30 UTC, carlobeltrame requested changes
Nice work! Ein paar Anmerkungen (wie immer), aber hoffentlich keine fundamentalen Änderungen mehr diesmal ;)

2021-03-05 15:30 UTC, carlobeltrame commented on backend/module/eCampApi/src/eCampApi/V1/Rpc/Index/IndexController.php
> -
Wir werden weiterhin eine Möglichkeit brauchen, um alle Template Camps abzurufen, um beim Camp erstellen eines auszuwählen. Dazu wäre ein Query Parameter auf `camps` denkbar: `/api/camps?template=true`. Durch diese Änderung funktioniert der Dialog "Create a camp" im Frontend nicht mehr, weil die Relation `.campTemplates` nicht mehr existiert.

2021-03-05 15:30 UTC, carlobeltrame commented on backend/module/eCampCore/data/prod/CampPrototypeData.php
> +<?php
Du nennst das Konzept der Vorlage nun überall Prototype. Ob es Template oder Prototype heisst ist mir persönlich egal, aber ich würde überall die gleiche Terminologie einsetzen. Wies aussieht wäre es am einfachsten, wenn du noch das `isTemplate` Flag auf `isPrototype` umbenennst.

2021-03-05 15:30 UTC, carlobeltrame commented on backend/module/eCampCore/data/prod/MaterialListPrototypeData.php
> +        $migros = $repository->findOneBy(['name' => 'Migros']);
Das sucht global in allen Camps nach einer solchen Materialliste, und wenn irgendwo schon eine existiert machts keine neue mehr. Müsste das nicht gescopet auf das Camp sein? Haben wir ein ähnliches Problem in anderen Fixtures? Brauchts ein separates Issue dafür?

2021-03-05 15:30 UTC, carlobeltrame commented on backend/module/eCampCore/src/ContentType/BaseContentTypeService.php
>              $q->join('row.contentNode', 'cn');
Diese Zeile auch ins innere `if` verschieben, der Join ist unnötig wenn man nicht filtert, oder?

2021-03-05 15:30 UTC, carlobeltrame commented on backend/module/eCampCore/src/ContentType/BaseContentTypeService.php
> -        }
Woher hat dieser Filter vormals gewusst, um welche Activity es gerade geht? Wo ist/war der Filter definiert?

2021-03-05 15:30 UTC, carlobeltrame commented on backend/module/eCampCore/src/ContentType/ContentTypeStrategyProvider.php
> +    public function get($contentTypeOrStrategyClass): ?ContentTypeStrategyInterface {
Wie wäre es wenn wir stattdessen den Parameter als `string` annotieren, sodass nie `null` zurückgegeben wird? Gibt es einen legitimen Grund, diese Methode mit etwas anderem als einem String aufzurufen?

2021-03-05 15:30 UTC, carlobeltrame commented on backend/module/eCampCore/src/Entity/AbstractContentNodeOwner.php
> +                $this->rootContentNode->setOwner(null);
Wenn man den EntityManager später flusht, weiss der dann dass er auch diesen ehemaligen RootNode updaten muss? Wie ist es wenn nach `setRootContentNode` erst mal nur `AbstractContentNodeOwner#save` aufgerufen wird? Gibts dann Inkonsistenzen oder ist das unproblematisch?

2021-03-05 15:30 UTC, carlobeltrame commented on backend/module/eCampCore/src/EntityFilter/CampFilter.php
> +            $campQ->expr()->eq('c.isTemplate', 1)
Das exponiert unter `/api/camps` alle Camp-Vorlagen. REST-mässig technisch gesehen korrekt. Aber macht das Sinn? Wäre die API nicht einfacher zu benutzen, wenn die Camp-Vorlagen nur mit dem Query-Parameter `?template=true` oder sonstwo separat auftauchen? Anders gefragt, sollte das Frontend wirklich alle CampTemplates herunterladen, wenn es nur die Liste der Camps des Benutzers anzeigen muss?

2021-03-05 15:30 UTC, carlobeltrame commented on backend/module/eCampCore/src/Entity/ContentNode.php
> +        return $this->allChildren;
Ich werde mit `myChildren` noch nicht so warm. Irgendwann kommt ja vielleicht die Methode `addMyChild` dazu...

Aktuell: `myChildren` und `allChildren`
Vorschlag 1: `children` und `descendants`
Vorschlag 2: `children` und `contentNodes`
Vorschlag 3: `children` und `tree`

2021-03-05 15:30 UTC, carlobeltrame commented on backend/module/eCampCore/src/Entity/ContentNode.php
> -    use ContentTypeStrategyProviderTrait;
Cool dass der ContentNode sich nicht mehr seine konkrete Strategie holen muss. Finde ich im Service besser aufgehoben. :+1:

2021-03-05 15:30 UTC, carlobeltrame commented on backend/module/eCampCore/src/Entity/ContentNode.php
> +     * @ORM\OneToMany(targetEntity="ContentNode", mappedBy="root")
Ah, nur der Root hat `allChildren`? Bei den anderen ist das leer?

2021-03-05 15:30 UTC, carlobeltrame commented on backend/module/eCampCore/src/Entity/ContentNode.php
> +                // if my new root is null, i'm the new root of my children
Dieser Kommentar beschreibt nicht, was hier abgeht. In der darauffolgenden Zeile wird der Root der direkten Nachkommen gesetzt, unabhängig davon welcher Wert `$root` gerade hat. Ausserdem kann `$root` gar nie `null` sein, höchstens `== $this`

2021-03-05 15:30 UTC, carlobeltrame commented on backend/module/eCampCore/test/Entity/ContentNodeTest.php
> +        $this->assertEquals($node, $child->getRoot());
```suggestion
        $this->assertEquals($node, $child->getRoot());
        $this->assertEquals(null, $node->getParent());
        $this->assertEquals($node, $node->getRoot());
```

2021-03-05 15:30 UTC, carlobeltrame commented on backend/module/eCampCore/src/EntityService/ActivityService.php
> +        $camp->addActivity($activity);
Good catch

2021-03-05 15:30 UTC, carlobeltrame commented on backend/module/eCampCore/src/EntityService/CategoryService.php
> +        CategoryContentTypeService $categoryContentTypeService
Solche Reihenfolge-Änderungen sind gefährlich, wenn jemand noch generierte AoT-Factories hat. Musst du jetzt nicht ändern, aber in Zukunft tendenziell eher die Reihenfolge beibehalten.

2021-03-05 15:30 UTC, carlobeltrame commented on backend/module/eCampCore/src/EntityService/ContentNodeService.php
> +            $childContentNode->setParent($contentNode);
Warum nicht `$contentNode->addChild` (bzw. `addMyChild` falls du meinen obigen Vorschlag ablehnst)?

2021-03-05 15:30 UTC, carlobeltrame commented on backend/module/eCampCore/src/Hydrator/ContentNodeHydrator.php
> +        // todo config
Wann wird das gemacht?

2021-03-05 15:30 UTC, carlobeltrame commented on backend/module/eCampCore/test/Entity/CategoryTest.php
> -    public function testCategoryContent(): void {
Ev. Test für RootContentNode in Category ergänzen

2021-03-05 15:30 UTC, carlobeltrame commented on backend/module/eCampCore/test/Entity/ContentNodeTest.php
> +    public function testContentNodeHirarchy(): void {
```suggestion
    public function testContentNodeHierarchy(): void {
```

2021-03-05 15:30 UTC, carlobeltrame commented on backend/module/eCampCore/test/Service/CampServiceTest.php
> +        $contentNodePrototypeLoader = new ContentNodePrototypeTestData($container);
Warum braucht diese Fixture den Service Container und die anderen nicht?

2021-03-05 15:30 UTC, carlobeltrame commented on backend/module/eCampLib/src/Acl/AclAssertion.php
> +        return false;
Ich würde hier eher eine Exception werfen, das ist ja wirklich kein nützlicher Use Case und sollte dem Entwickler unbedingt gemeldet werden.

2021-03-05 19:53 UTC, pmattmann commented on backend/module/eCampCore/src/Entity/ContentNode.php
> +     * @ORM\OneToMany(targetEntity="ContentNode", mappedBy="root")
yes; ist inverse-collection vom root-pointer

2021-03-05 19:55 UTC, pmattmann commented on backend/module/eCampCore/src/Entity/ContentNode.php
> +                // if my new root is null, i'm the new root of my children
kommentar kommt weg;
habe ich wohl den code refactored, nicht aber den kommentar

2021-03-05 20:05 UTC, pmattmann commented on backend/module/eCampCore/src/EntityService/ContentNodeService.php
> +            $childContentNode->setParent($contentNode);
Bei **setParent** scheint mir die Logik verständlicher (inkl. anpassen des eigenen root-zeiger; und jenen aller meiner Kinder).
Aber was ich anbieten kann:
```php
  public function addChild($child) {
    $child->setParent($this);
  }

  public function removeChild($child) {
    $child->setParent(null);
  }
```
Jedoch nur als syntactic sugar. Logik möchte ich eher nicht umbauen.

2021-03-05 20:10 UTC, pmattmann commented on backend/module/eCampCore/test/Service/CampServiceTest.php
> +        $contentNodePrototypeLoader = new ContentNodePrototypeTestData($container);
goot catch... wird nicht mehr benötigt...

2021-03-05 20:23 UTC, pmattmann commented on backend/module/eCampCore/src/Entity/AbstractContentNodeOwner.php
> +                $this->rootContentNode->setOwner(null);
Das ist unproblematisch. Der EntityManager kenne alle geladenen Objekte und prüft diese beim Speichern auf Änderungen.

2021-03-05 20:37 UTC, pmattmann commented on backend/module/eCampCore/src/ContentType/ContentTypeStrategyProvider.php
> +    public function get($contentTypeOrStrategyClass): ?ContentTypeStrategyInterface {
Die get()-Methode wird mit **ContentType** als Argument verwendet. Ich habe es nun darauf eingeschränkt.

2021-03-05 20:39 UTC, pmattmann commented on backend/module/eCampCore/src/ContentType/BaseContentTypeService.php
>              $q->join('row.contentNode', 'cn');
join wird überhaupt nicht mehr benötigt.

2021-03-05 20:43 UTC, pmattmann commented on backend/module/eCampCore/src/ContentType/BaseContentTypeService.php
> -        }
ContentNode hat auf Activity gezeigt.
Activity auf Camp.
Camp-Filter schränkt die Sicht von User ein.

Durch diese Joins wurden die möglichen sichtbaren ContentTypes eingeschränkt.

2021-03-05 20:44 UTC, pmattmann commented on backend/module/eCampCore/src/EntityFilter/CampFilter.php
> +            $campQ->expr()->eq('c.isTemplate', 1)
Wäre denkbar. Aber nicht hier.
CampFilter schränkt die Sicht des Users auf die Datenbank ein.
Wenn wir das machen wollen, dann implementiere ich das im CampService.

2021-03-05 21:19 UTC, carlobeltrame commented on backend/module/eCampCore/src/EntityService/ContentNodeService.php
> +            $childContentNode->setParent($contentNode);
Ah, ja, ich verstehe. Kannst du hinzufügen oder so belassen wies ist, so weit hatte ich nicht mitgedacht. Habe nur ein Child gesehen das den Parent direkt gesetzt bekommt, das vermeiden wir ja sonst normalerweise.

2021-03-06 10:21 UTC, pmattmann commented on backend/module/eCampCore/data/prod/MaterialListPrototypeData.php
> +        $migros = $repository->findOneBy(['name' => 'Migros']);
wird korrigiert

2021-03-06 10:22 UTC, pmattmann commented on backend/module/eCampCore/src/Entity/ContentNode.php
> +        return $this->allChildren;
Kann ich gerne anpassen - Präferenzen?

2021-03-06 11:02 UTC, manuelmeister commented on backend/module/eCampCore/src/Entity/ContentNode.php
> +        return $this->allChildren;
Ich würde für Vorschlag 1 stimmen. Ist es korrekt, dass `children` eine Teilmenge von `descendants` ist?

2021-03-06 11:22 UTC, pmattmann commented on backend/module/eCampCore/src/Entity/ContentNode.php
> +        return $this->allChildren;
Das ist nur für den Root-Node korrekt; für alle anderen nodes ist die List `allChildren` / `descendants`  leer.

2021-03-06 12:23 UTC, manuelmeister commented on backend/module/eCampCore/src/Entity/ContentNode.php
> +        return $this->allChildren;
Ah okay. Dann wäre ich wohl eher für rootDescendants.

2021-03-06 12:46 UTC, pmattmann commented on backend/module/eCampCore/src/Hydrator/ContentNodeHydrator.php
> +        // todo config
erledigt: dd8267d

2021-03-06 16:40 UTC, carlobeltrame commented on backend/module/eCampCore/src/EntityService/ContentNodeService.php
> +            $parent = $this->findRelatedEntity(ContentNode::class, $data, 'parentId');
Hängt das den neuen ContentNode einfach blind an den Parent an? Müssten wir da validieren, dass der User Schreibrechte auf das Camp vom Parent hat? Und gleiches beim Owner?

2021-03-07 11:58 UTC, pmattmann commented on backend/module/eCampCore/src/EntityService/ContentNodeService.php
> +            $parent = $this->findRelatedEntity(ContentNode::class, $data, 'parentId');
Naja - nicht blind an den Parent, mindestens "Sehen" muss man ihn können.
`AbstractEntityService.findRelatedEntity` gibt nur Entitäten zurück, für welche man mindestens `FETCH`-Rechte hat.
Siehe:
- `AbstractEntityService.findRelatedEntity`
- `AbstractEntityService.findEntity`
- `AbstractEntityService.getQuerySingleResult`
  - hier wird `assertAllowed($row, Acl::REST_PRIVILEGE_FETCH);` geprüft

Aber du hast recht, Schreibtrecht muss zusätzlich geprüft werden. Siehe a105fd0

2021-03-07 17:49 UTC, carlobeltrame approved these changes
Super, danke! Ich mach mich dannmal dran, dass man wieder mehrere ContentNodes in einer Activity haben kann :)

2021-03-11 20:52 UTC, BacLuc commented
Super, jetzt können sich auch andere einen Teil des Kuchens schnappen und loslegen.

Habe es getestet, was nicht funktioniert:
- [ ] Man kann nur einen ContentNode (Story, MaterialList) auf einer Activity haben.
Wenn man einen neuen hinzufügt, wird der alte gelöscht.
- [ ] Bei MaterialList kann man für die Activity keine Items hinzufügen
- [ ] print geht kaputt

Das sollte man später noch fixen.

Die Logs vom Print:

`ecamp3-print              |  ERROR  Error in fetch(): this.activity.activityCategory is not a function
ecamp3-print              | 
ecamp3-print              |   at VueComponent.fetch (components/program-schedule-entry.js:131:49)
ecamp3-print              |   at processTicksAndRejections (internal/process/task_queues.js:93:5)
ecamp3-print              |   at async VueComponent.serverPrefetch (server.js:1461:5)
ecamp3-print              |   at async Promise.all (index 0)
ecamp3-print              | 
ecamp3-print              | 
ecamp3-print              |  ERROR  [Vue warn]: Error in render: "TypeError: Cannot read property 'name' of null"
ecamp3-print              | 
ecamp3-print              | found in
ecamp3-print              | 
ecamp3-print              | ---> <ProgramScheduleEntry> at components/ProgramScheduleEntry.vue
ecamp3-print              |        <ProgramDay> at components/ProgramDay.vue
ecamp3-print              |          <ProgramPeriod> at components/ProgramPeriod.vue
ecamp3-print              |            <Program> at components/Program.vue
ecamp3-print              |              <Pages/index.vue> at pages/index.vue
ecamp3-print              |                <Nuxt>
ecamp3-print              |                  <VMain>
ecamp3-print              |                    <VApp>
ecamp3-print              |                      <Layouts/default.vue> at layouts/default.vue
ecamp3-print              |                        <Root>
ecamp3-print              | 
ecamp3-print              | 
ecamp3-print              |  ERROR  Error in fetch(): this.activity.activityCategory is not a function
ecamp3-print              | 
ecamp3-print              |   at VueComponent.fetch (components/program-schedule-entry.js:131:49)
ecamp3-print              |   at processTicksAndRejections (internal/process/task_queues.js:93:5)
ecamp3-print              |   at async VueComponent.serverPrefetch (server.js:1461:5)
ecamp3-print              |   at async Promise.all (index 0)
ecamp3-print              | 
ecamp3-print              | 
ecamp3-print              |  ERROR  [Vue warn]: Error in render: "TypeError: Cannot read property 'name' of null"
ecamp3-print              | 
ecamp3-print              | found in
ecamp3-print              | 
ecamp3-print              | ---> <ProgramScheduleEntry> at components/ProgramScheduleEntry.vue
ecamp3-print              |        <ProgramDay> at components/ProgramDay.vue
ecamp3-print              |          <ProgramPeriod> at components/ProgramPeriod.vue
ecamp3-print              |            <Program> at components/Program.vue
ecamp3-print              |              <Pages/index.vue> at pages/index.vue
ecamp3-print              |                <Nuxt>
ecamp3-print              |                  <VMain>
ecamp3-print              |                    <VApp>
ecamp3-print              |                      <Layouts/default.vue> at layouts/default.vue
ecamp3-print              |                        <Root>
`

2021-03-11 21:05 UTC, BacLuc approved these changes

2021-03-13 20:20 UTC, pmattmann commented
> * [ ]  Man kann nur einen ContentNode (Story, MaterialList) auf einer Activity haben.
>   Wenn man einen neuen hinzufügt, wird der alte gelöscht.
> * [x]  Bei MaterialList kann man für die Activity keine Items hinzufügen
> * [x]  print geht kaputt

MaterialList & Print habe ich geflickt.
Mehrere ContentNode geht erst wieder, wenn wir den ContentType "Column" haben.
-> das ist "absichtlich" kaputt ;)

2021-03-13 20:24 UTC, merged