refactor/CampCollaboration: rename STATUS_LEFT to STATUS_INACTIVE
ecamp/ecamp3 pull request #1108
Opened 2021-03-18 19:59 UTC by BacLuc

Issue: #631

2021-03-18 21:08 UTC, pmattmann requested changes

2021-03-18 21:08 UTC, pmattmann commented on backend/module/eCampCore/src/EntityService/CampCollaborationService.php
>              $campCollaboration = $this->updateLeft($campCollaboration, $data);
Ich würde diese Methode ebenfalls unbenennen

2021-03-21 14:51 UTC, BacLuc commented on backend/module/eCampCore/src/EntityService/CampCollaborationService.php
>              $campCollaboration = $this->updateLeft($campCollaboration, $data);
Jup, das habe ich vergessen.
Ist gefixt

2021-03-21 15:50 UTC, pmattmann requested changes

2021-03-21 15:50 UTC, pmattmann commented on frontend/src/views/activity/Activity.vue
> +        const left = value.status === 'inactive'
Sorry, noch einen gefunden...

2021-03-23 20:38 UTC, pmattmann commented on frontend/src/views/activity/Activity.vue
>          const text = value.user().displayName + (left ? (' (' + this.$tc('entity.campCollaboration.campLeft')) + ')' : '')
one more

2021-04-03 15:28 UTC, pmattmann approved these changes

2021-04-04 18:32 UTC, carlobeltrame approved these changes

2021-04-04 18:32 UTC, merged