Use dateinterval in periodservice
ecamp/ecamp3 pull request #1191
Opened 2021-04-03 15:18 UTC by BacLuc

2021-04-03 15:44 UTC, pmattmann reviewed
Cool, danke für die Move-ScheduleEntry-Tests.

Magst du für `EDateInterval` auch Test schreiben?

2021-04-03 16:56 UTC, BacLuc commented on backend/module/eCampLib/test/Types/EDateIntervalTest.php
> +/**
php-cs-fixer will das jetzt, hoffentlich kommt bald das update auf 2.18.5, das diese kleinen Bugs fixed.

2021-04-03 19:33 UTC, pmattmann approved these changes

2021-04-04 09:53 UTC, carlobeltrame requested changes

2021-04-04 09:53 UTC, carlobeltrame commented on backend/module/eCampLib/src/Types/EDateInterval.php
> +    public static function totalSecondsOf(\DateInterval $interval): int {
Gibt es keine native Methode dafür? Wieso nicht? Kann das zu Problemen bei Schalttagen oder Schaltsekunden führen? Könntest du statt new DateTime ein fixes Datum nehmen damit diese Methode wirklich deterministisch wird?

2021-04-05 08:48 UTC, BacLuc commented on backend/module/eCampLib/src/Types/EDateInterval.php
> +    public static function totalSecondsOf(\DateInterval $interval): int {
Ich habe leider nichts gefunden, siehe https://www.php.net/manual/en/dateinterval.format.php
Schalttage/Schaltsekunden sollten kein Problem sein, da das Interval gleich bleiben sollte.
Ein fixes Datum kann ich nehmen.

2021-04-05 17:52 UTC, carlobeltrame approved these changes
Merci!

2021-04-05 17:52 UTC, merged