v-data-table for material items
ecamp/ecamp3 pull request #1274
Opened 2021-04-18 10:32 UTC by usu

WIP

2021-04-27 19:23 UTC, pmattmann reviewed
Mir ist folgendes aufgefallen:
- Material-View funktioniert im Mobile-Modus nicht komplett (JS-Errors)

Zugleich habe ich mich folgendes gefragt. Wenn ich die Material-Liste ändern will, muss ich nach Artikel gruppieren, damit die Materail-Liste als Control erscheint.
Das erscheint mir nicht besonders intuitiv.

2021-04-28 05:24 UTC, usu commented
> Zugleich habe ich mich folgendes gefragt. Wenn ich die Material-Liste ändern will, muss ich nach Artikel gruppieren, damit die Materail-Liste als Control erscheint.
> Das erscheint mir nicht besonders intuitiv.

Yes, true. Ist leider so wie v-data-table von Haus aus funktioniert: Wenn nach einer Spalte gruppiert wird, wird sie aus der Tabelle entfernt. Du musst aber nicht zwingend nach einer anderen Spalte gruppieren, sondern kannst die Gruppierung auch entfernen. Mögliche kurzfristige Lösungen:
- Tabelle beim Laden der Seite ungruppiert anzeigen. Eventuell oben mit einem prominenten Switch zum Ein-/Ausschalten der Gruppierung.
- Edit Button immer anzeigen, auch im Desktop-View
- Verhalten von v-data-table versuchen zu ändern. Eventuell möglich über die Slots, aber wahrscheinlich ziemlich "hacky"

2021-04-28 16:06 UTC, usu commented
@pmattmann Hab mal ein paar Improvements zu Usability versucht. Gruppieren kann man nun mit einem Switch ein-/ausschalten (ist expliziter). 

In der Mobile-Ansicht ist gruppieren nach Liste immer an (spart Platz). Dafür gibts da auch immer ein Edit-Button, mit der die Liste geändert werden kann.

2021-04-28 17:07 UTC, pmattmann approved these changes
Cool!

Ein paar Punkte gibt es noch - können aber auch als neue Issues behandelt werden:
- Wenn gruppiert nach Liste, sortieren nach Artikel verhält sich seltsam
- Mobile-View
  - "Add new item" in Mobile-View, neuer Eintrag erscheint nicht
  - Könnten wir "Edit" und "Activity"-Link in der selben Spalte haben? Spart Platz.

2021-04-30 05:27 UTC, usu commented
> Mobile-View
> * "Add new item" in Mobile-View, neuer Eintrag erscheint nicht
> * Könnten wir "Edit" und "Activity"-Link in der selben Spalte haben? Spart Platz.

Resolved

2021-04-30 05:28 UTC, usu commented
> * Wenn gruppiert nach Liste, sortieren nach Artikel verhält sich seltsam

@pmattmann Kannst du dazu noch etwas genauer beschreiben, was du meinst? V-data-table funktioniert so, dass Gruppieren stärker ist als Sortieren, das heisst sortiert nur innerhalb der Gruppe, aber löst die Gruppierung nicht auf. Meinst du das?

2021-04-30 10:30 UTC, pmattmann commented
> > * Wenn gruppiert nach Liste, sortieren nach Artikel verhält sich seltsam
> 
> @pmattmann Kannst du dazu noch etwas genauer beschreiben, was du meinst? V-data-table funktioniert so, dass Gruppieren stärker ist als Sortieren, das heisst sortiert nur innerhalb der Gruppe, aber löst die Gruppierung nicht auf. Meinst du das?

Ich glaube ich war verwirrt, weil auch die Gruppierungen selber sich verschobene haben.
Ich würds für den Moment aber so lassen.

2021-05-03 16:39 UTC, carlobeltrame requested changes

2021-05-03 16:39 UTC, carlobeltrame commented on backend/module/eCampCore/src/EntityService/AbstractEntityService.php
> +            $data = (object) array_merge((array) $queryParams, (array) $data);
Ich glaube das erlaubt es aktuell, Validierungen und Filter zu umgehen. Ungefähr so (nicht getestet): Im POST body den Parameter einfach weglassen und stattdessen als GET parameter einen illegalen Wert senden. Das funktioniert natürlich nur mit optionalen Parametern, aber bei PATCH ist alles optional.

2021-05-03 16:39 UTC, carlobeltrame commented on backend/module/eCampCore/src/EntityService/AbstractEntityService.php
> +            $data = (object) array_merge((array) $queryParams, (array) $data);
Ausserdem sollten wir solche Logik im abstract service unbedingt gut unit-testen.

2021-05-04 16:29 UTC, usu commented on backend/module/eCampCore/src/EntityService/AbstractEntityService.php
> +            $data = (object) array_merge((array) $queryParams, (array) $data);
Hmm, valid point. 

Injection von Query-Parameters habe ich nur beim create/POST eingebaut, bei update/PATCH also kein Problem. Aber illegale Werte gehen natürlich auch bei create/POST.

Schau ich mir an, wie man die Validierung der Query Params einbinden kann. Haben andere auch schon angeschaut, vielleicht kann ich das direkt von da übernehmen:
https://gist.github.com/RubtsovAV/fcc2701ee4c7e8dbe125dbea880012b2
https://github.com/eth8505/laminas-api-tools-rest-queryparam-validation

2021-05-04 18:52 UTC, usu commented on backend/module/eCampCore/src/EntityService/AbstractEntityService.php
> +        $q->addOrderBy('row.createTime');
Check if we extend of BaseEntity

2021-05-07 16:18 UTC, carlobeltrame approved these changes

2021-05-07 16:18 UTC, carlobeltrame commented on backend/module/eCampApi/src/eCampApi/PostQueryParamsInjectListener.php
> +class PostQueryParamsInjectListener implements ListenerAggregateInterface {
Sieht gut aus so. Trotzdem würde ich diesen Mechanismus noch ausgiebig testen, z.B. dass der POST body Vorrang hat, und was passiert wenn eine oder beide der Parameter-Quellen eine oder verschiedene Validierungen triggern. Von mir aus kannst du dafür aber auch ein Issue erstellen und das hier mal mergen, vielleicht mach ichs dann sogar selber irgendwann.

2021-05-08 04:12 UTC, usu commented on backend/module/eCampApi/src/eCampApi/PostQueryParamsInjectListener.php
> +class PostQueryParamsInjectListener implements ListenerAggregateInterface {
Agree. Erfasst in #1274 .

Müsst evt. nicht im End-to-end Test sein sondern könnte auch ein Unit-Test des Listeners sein. Bezüglich Unit-Test fehlt im Backend sowieso noch dass ein oder andere.

2021-05-08 04:30 UTC, merged