Extend ci for api platform
ecamp/ecamp3 pull request #1681
Opened 2021-07-18 16:18 UTC by BacLuc

- [x] check dependencies of api platform
- [x] validate composer.loc of api platform
- [x] cache composer packages (does not help much, because the main time consumer is buliding the docker image)
- [x] Report Coverage

2021-07-25 18:44 UTC, carlobeltrame requested changes

2021-07-25 18:44 UTC, carlobeltrame commented on .github/workflows/check-dependencies.yml
> +          chmod +w backend
Das brauchts wohl nicht, oder?

2021-07-28 17:19 UTC, BacLuc commented on .github/workflows/check-dependencies.yml
> +          chmod +w backend
Wahrscheinlich nur für backend/vendor nötig.
Schon lange her, kann ich nochmals überprüfen

2021-07-28 19:11 UTC, BacLuc commented
Ich werde diesen oder #1728 rebasen müssen.
Mache ich vor dem merge.

2021-07-28 20:51 UTC, carlobeltrame approved these changes

2021-07-29 20:28 UTC, carlobeltrame approved these changes

2021-07-29 20:29 UTC, pmattmann approved these changes

2021-07-29 20:29 UTC, merged