Support templated links in API entrypoint
ecamp/ecamp3 pull request #2012
Opened 2021-10-02 20:43 UTC by simfeld

TODO:

- [ ] Add API hostname? Or is `/camps` ok?
- [ ] For invitations we have `GET /invitations/{inviteKey}/find` which is reflected in the current output, but also `PATCH /invitations/{inviteKey}/accept` and `PATCH /invitations/{inviteKey}/reject`. Is it correct to only care about `GET`? The templated link from the previous backend was `http://localhost:3001/api/invitations{/inviteKey}{/campCollaborationId}{/action}`

2021-10-02 21:26 UTC, BacLuc commented
I would say it's ok to only have a templated link for GET /invitations/{inviteKey}/find.
The current goal is to get most of the frontend working. We can add templated links for such special cases later

2021-10-02 21:38 UTC, BacLuc reviewed
Hierfür wäre ein Test super.

2021-10-02 21:38 UTC, BacLuc commented on api/src/Serializer/Normalizer/URITemplateNormalizer.php
> +                $resourceName = $this->snakeToCamel(explode('/', $pathName)[1]);
do the paths always have a slash (so start with /)?
Else we would need a length check for the exploded path

2021-10-02 21:38 UTC, BacLuc commented on api/src/Serializer/Normalizer/URITemplateNormalizer.php
> +                while ($index < count($parameters)) {
I would do that with a for loop
(or maybe even with a foreach($parameters as $index => $parameter))

2021-10-02 21:38 UTC, BacLuc commented on api/src/Serializer/Normalizer/URITemplateNormalizer.php
> +    private function snakeToCamel($input) {
die methode könnte static sein

2021-10-02 22:28 UTC, manuelmeister commented on api/src/Serializer/Normalizer/URITemplateNormalizer.php
> +            $url = isset($path['itemUrl']) ? $path['itemUrl'] : $path['collectionUrl'];
```suggestion
            $url = $path['itemUrl']) ?? $path['collectionUrl'];
```

2021-10-02 23:00 UTC, carlobeltrame requested changes

2021-10-02 23:00 UTC, carlobeltrame commented on api/src/Serializer/Normalizer/URITemplateNormalizer.php
> +                $resourceName = $this->snakeToCamel(explode('/', $pathName)[1]);
@simfeld this will not work when we use a path_prefix, like in all the `/content_node/xyzs/{id}` endpoints. The resource name should be somewhere in the openApi docs you already have, is it not?

2021-10-02 23:01 UTC, carlobeltrame commented
It is configurable within API Platform whether to output full absolute URIs or relative `/camps` URIs, and we have it configured for the relative ones. So for us, relative URIs should be fine.

2021-10-03 01:38 UTC, BacLuc commented on api/src/Serializer/Normalizer/URITemplateNormalizer.php
> +    public function __construct(private NormalizerInterface $decorated, private ResourceMetadataFactoryInterface $resourceMetadataFactory, private IriConverterInterface $iriConverter, private UrlGene
ich würde die parameter auf einzelne zeilen packen

2021-10-03 10:06 UTC, pmattmann approved these changes

2021-10-03 11:24 UTC, BacLuc commented on api/src/Serializer/Normalizer/URITemplateNormalizer.php
> +    public function __construct(private NormalizerInterface $decorated, private ResourceMetadataFactoryInterface $resourceMetadataFactory, private IriConverterInterface $iriConverter, private UrlGene
done

2021-10-03 11:40 UTC, carlobeltrame approved these changes

2021-10-03 11:40 UTC, merged