Fix camp role mixin
ecamp/ecamp3 pull request #2121
Opened 2021-10-19 19:35 UTC by BacLuc

2021-10-23 14:23 UTC, manuelmeister approved these changes

2021-10-23 17:33 UTC, carlobeltrame requested changes

2021-10-23 17:33 UTC, carlobeltrame commented on api/tests/Api/Camps/ListCampsTest.php
> +    public function testListCampsDoesNotIncludeCampCollaborationsAndUsers() {
Wenn du die User nur beim Camp Item embeddest und nicht in der Liste, kann es sein dass hal-json-vuex später einen einzelnen User nachladen will, was nicht erlaubt ist. Ich würde es immer embedden. Bisher haben wir glaube ich immer genau denselben payload in der liste und beim item.

2021-10-24 14:35 UTC, BacLuc commented on api/tests/Api/Camps/ListCampsTest.php
> +    public function testListCampsDoesNotIncludeCampCollaborationsAndUsers() {
Bisher haben wir das embedding nur bei den item operations definiert.
Und wenn man die Liste der Camps holt (zum glück schon gefiltert nach denen, auf die ich zugriff habe), dann möchte man nicht unbedingt schon den ganzen baum laden.

Ich hätte gesagt, dass wenn jemand die user braucht, dann soll er dafür sorgen, dass this.api.reload(camp) gemacht wird.
Aber wir können sonst auch dafür sorgen, dass wir für get auf collection und auf item operations den gleichen normalization_context haben.

2021-10-24 18:13 UTC, carlobeltrame commented on api/tests/Api/Camps/ListCampsTest.php
> +    public function testListCampsDoesNotIncludeCampCollaborationsAndUsers() {
I see. Ob wir allgemein in Listen andere Inhalte / Embeddings haben wollen können wir gerne mal noch an einem Meeting besprechen.
In diesem spezifischen Fall fände ich es seltsam, wenn im API-Client Meta-Wissen nötig wäre im Stil von "wenn du die User des Camps willst musst du zwingend das Camp neu laden". Also entweder würde ich eben den User immer im Camp und in der Collaboration embedden, oder die Security-Regel auf Usern lockern.

2021-10-24 19:24 UTC, BacLuc commented on api/tests/Api/Camps/ListCampsTest.php
> +    public function testListCampsDoesNotIncludeCampCollaborationsAndUsers() {
Vorschlag: ich lösche den test bei der Liste, und wir diskutieren beim nächsten Meeting, wie wir mit normalization_context bei get für item/collection umgehen wollen, und ob wir die security beim user weiter öffnen wollen.

Dann mergen wir das, weil es ermöglicht es, die anderen sachen auf der Admin.vue View zu fixen (Category erstellen, Materiallist erstellen. Plus die Collaborators Seite kann man so auch fixen. Sonst ist man immer gast, und hat keine rechte.
Da liegt bei mir lokal schon was herum.

2021-10-24 20:12 UTC, carlobeltrame commented on api/tests/Api/Camps/ListCampsTest.php
> +    public function testListCampsDoesNotIncludeCampCollaborationsAndUsers() {
Okay, passt für mich

2021-10-25 08:09 UTC, BacLuc commented on api/tests/Api/Camps/ListCampsTest.php
> +    public function testListCampsDoesNotIncludeCampCollaborationsAndUsers() {
Test in ListCampsTest ist gelöscht.

2021-10-25 17:24 UTC, pmattmann approved these changes

2021-10-25 19:25 UTC, carlobeltrame approved these changes

2021-10-25 19:25 UTC, merged