Adapt frontend to api platform
ecamp/ecamp3 pull request #2149
Opened 2021-10-25 21:25 UTC by BacLuc

Ich bin gerade am durchgehen, was im Frontend noch nicht funktioniert.
Ist sicher nicht alles perfekt, aber damit ihr wisst, woran ich bin. (Und es nicht doppelt macht)

2021-10-26 06:45 UTC, manuelmeister commented on frontend/src/views/camp/Collaborators.vue
> +      this.api.href(this.api.get(), 'campCollaborations')
Cool, das hatte ich bis jetzt nicht im Einsatz gesehen.

2021-10-26 06:47 UTC, manuelmeister commented on frontend/src/components/activity/ButtonNestedContentNodeAdd.vue
> +      }
Wie wollen wir hier in Zukunft vorgehen? Wird das bei weiteren ContentNodes noch weiter wachsen?

2021-10-26 06:48 UTC, manuelmeister approved these changes

2021-10-26 10:39 UTC, BacLuc commented on frontend/src/components/activity/ButtonNestedContentNodeAdd.vue
> +      }
Das ist momentan noch ein hack. Evtl sollte man irgendwie aus dem backend die routen mitgeben.

2021-10-26 13:38 UTC, carlobeltrame requested changes

2021-10-26 13:38 UTC, carlobeltrame commented on frontend/src/components/activity/ButtonNestedContentNodeAdd.vue
> +      }
Oder ein "Modul-" bzw. "Plugin-System" für Content Types im Frontend einführen. Im ColumnLayout-Modul wäre dann definiert, was der API-Name ist und welche additionalFields nötig sind, etc.

2021-10-26 13:38 UTC, carlobeltrame commented on frontend/src/components/activity/content/ColumnLayout.vue
> +        columns: this.contentNode?.columns()._storeData.items.map(column => ({
Wenn das Fragezeichen wirklich nötig ist, ist es doch auch bei den danach gechainten Aufrufen nötig, nicht? Es kann ja `null` dabei rauskommen. Ausserdem ist `_storeData` internal, das solltest du eigentlich nie verwenden.

2021-10-26 13:38 UTC, carlobeltrame commented on frontend/src/components/activity/content/ColumnLayout.vue
> +      return keyBy(this.contentNode?.columns()._storeData.items || [], 'slot')
Wenn das Fragezeichen wirklich nötig ist, ist es doch auch bei den danach gechainten Aufrufen nötig, nicht? Es kann ja null dabei rauskommen. Ausserdem ist `_storeData` internal, das solltest du eigentlich nie verwenden.

2021-10-26 13:38 UTC, carlobeltrame commented on frontend/src/components/activity/content/ColumnLayout.vue
> +  <v-row v-if="columns" no-gutters>
War das vorher nicht besser? Bzw. jetzt müssten wir einfach ein computed `loading` machen, welches checkt ob `contentNode._meta.loading` oder `contentNode.columns()._meta.loading` oder ob eines von `contentNode.columns().items` noch am laden ist. Dieses Pattern von nested Loading Checks ist mir beim Picasso PDF drucken auch aufgefallen, ich denke da brauchen wir dann bald mal eine Erweiterung in hal-json-vuex dafür, die das einfacher macht.
Ich finde, wir sollten uns nicht darauf verlassen dass die Columns immer mitkommen. Besonders wenn wir uns nicht dafür entscheiden, in Listen und in einzelnen Items immer genau dasselbe zu embedden, kann es sein, dass die embeddeten Objekte mal da sind und mal nicht.

2021-10-26 13:38 UTC, carlobeltrame commented on frontend/src/components/activity/content/ColumnLayout.vue
> +      if (!this.columns) {
Hier würde ich dann auch auf das computed `loading` zurückgreifen.

2021-10-26 13:38 UTC, carlobeltrame commented on frontend/src/components/activity/content/ColumnLayout.vue
> +      return Object.keys(this.columns).length
Ich verstehe nicht ganz was du hier berechnest - warum verwendest du sonst jeweils `columns().items`, aber hier `Object.keys(columns)`?

2021-10-26 13:38 UTC, carlobeltrame commented on frontend/src/components/activity/content/columnLayout/ColumnOperations.vue
> +      return this.contentNode?.columns()._storeData.items || []
`_storeData` ist internal, das solltest du eigentlich nie verwenden.

2021-10-26 13:38 UTC, carlobeltrame commented on frontend/src/components/camp/CollaboratorListItem.vue
> +      }).then(postUrl => this.api.patch(postUrl + '/resend_invitation', {}))
Aha, also müssten wir noch den `{action}` Parameter auf der API ergänzen? Oder noch besser die `resend_invitation` Route selber?

2021-10-26 13:38 UTC, carlobeltrame commented on frontend/src/components/dialog/DialogCategoryCreate.vue
> +        this.api.reload(this.camp.categories())
Hast du irgendeine Ahnung warum vorher das ganze Camp neu geladen werden musste?

2021-10-26 13:38 UTC, carlobeltrame commented on frontend/src/components/dialog/DialogMaterialListCreate.vue
> +      entityUri: this.api.get().materialList
Diese Schreibweise ist etwas unerwartet für mich... Verträgt es in dem Fall der DialogBase wenn man da ein Objekt reingibt? `{ href: '/material-lists' }`
Und seit wann sind die Keys im API Root Endpoint wieder in Singular?

2021-10-26 16:58 UTC, BacLuc commented on frontend/src/components/activity/content/ColumnLayout.vue
> +        columns: this.contentNode?.columns()._storeData.items.map(column => ({
Ich bin noch nicht ganz damit klar gekommen, wie diese columns da rauskommen. Es ist momentan ein objekt, mit zahlen als properties glaube ich.
Ich wollte einfach mal einen schritt weiter, und schauen, was dahinter noch alles schief läuft. (z.b. dass man die ContentNodes ausser ColumnLayout erstellen kann, diese aber nicht angezeigt werden).

Falls der rest bei der Invitation etc ok ist, und wir das separat wollen, dann nehme ich diesen Teil aus dem PR raus, und mache einen seperaten, der sich dem editieren einer Activity/Category annimmt.

2021-10-26 16:59 UTC, BacLuc commented on frontend/src/components/activity/content/ColumnLayout.vue
> +      return keyBy(this.contentNode?.columns()._storeData.items || [], 'slot')
https://github.com/ecamp/ecamp3/pull/2149#discussion_r736746440

2021-10-26 16:59 UTC, BacLuc commented on frontend/src/components/activity/content/ColumnLayout.vue
> +  <v-row v-if="columns" no-gutters>
https://github.com/ecamp/ecamp3/pull/2149#discussion_r736746440

2021-10-26 16:59 UTC, BacLuc commented on frontend/src/components/activity/content/ColumnLayout.vue
> +      if (!this.columns) {
https://github.com/ecamp/ecamp3/pull/2149#discussion_r736746440

2021-10-26 16:59 UTC, BacLuc commented on frontend/src/components/activity/content/ColumnLayout.vue
> +      return Object.keys(this.columns).length
https://github.com/ecamp/ecamp3/pull/2149#discussion_r736746440

2021-10-26 16:59 UTC, BacLuc commented on frontend/src/components/activity/content/columnLayout/ColumnOperations.vue
> +      return this.contentNode?.columns()._storeData.items || []
https://github.com/ecamp/ecamp3/pull/2149#discussion_r736746440

2021-10-26 17:01 UTC, BacLuc commented on frontend/src/components/camp/CollaboratorListItem.vue
> +      }).then(postUrl => this.api.patch(postUrl + '/resend_invitation', {}))
Jup, das kommt noch nicht sauber mit beim detektrieren der Path parameter/routen (wie das auch immer heisst). Mal schauen ob ich das bald noch mache.

2021-10-26 17:03 UTC, BacLuc commented on frontend/src/components/dialog/DialogCategoryCreate.vue
> +        this.api.reload(this.camp.categories())
v.a habe ich keine Ahung, warum dann die categories nicht neu geladen wurden. Ich hätte erwartet, dass beim laden des camps die categories auch neu geladen werden.
Evtl sind sie nicht embedded, und die nach camp gefilterte collection url ist schon gecached...

2021-10-26 17:05 UTC, BacLuc commented on frontend/src/components/dialog/DialogMaterialListCreate.vue
> +      entityUri: this.api.get().materialList
Sollte ich wahrscheinlich nochmals testen, ging evtl bisschen schnell.

2021-10-27 09:46 UTC, carlobeltrame commented on frontend/src/components/activity/content/ColumnLayout.vue
> +        columns: this.contentNode?.columns()._storeData.items.map(column => ({
Ja, fände ich ok

2021-11-02 14:22 UTC, closed without merging