VS Code: use php-cs-fixer installed by composer
ecamp/ecamp3 pull request #2197
Opened 2021-11-07 12:37 UTC by pmattmann

verhindert, dass man php-cs-fixer global installieren muss

2021-11-07 16:23 UTC, BacLuc approved these changes

2021-11-09 18:01 UTC, usu requested changes
Könntest du `.vscode/api/settings.json` auch gleich nachziehen? Dann funktioniert es auch, wenn man VSCode nur aus dem `api` subfolder startet.

2021-11-14 14:51 UTC, pmattmann commented
> Könntest du `.vscode/api/settings.json` auch gleich nachziehen? Dann funktioniert es auch, wenn man VSCode nur aus dem `api` subfolder startet.

Da sollte es nicht notwendig sein. Das Plugin "php cs fixer" sucht das Binary standardmässig unter "${workspaceFolder}/vendor/bin/php-cs-fixer" - was ja dann gerade stimmt.

2021-11-14 15:00 UTC, usu approved these changes

2021-11-14 15:00 UTC, merged