chore (print): table layout instead of flex layout for content nodes
ecamp/ecamp3 pull request #2654
Opened 2022-04-24 10:43 UTC by usu

Use table layout for ColumnLayout and for Storyboard instead of flex layout

For Storyboard, this fixes the issue with inconsistent column widths. For ColumnLayout no change at the moment, but probably easier to generate consistent results with PagedJS & Chrome.

2022-04-24 20:25 UTC, pmattmann approved these changes

2022-05-04 15:54 UTC, carlobeltrame requested changes
Sieht visuell sehr gut aus, aber jetzt können lange Storyboards gar nicht mehr über mehrere Seiten umbrechen. Ich habe als User jetzt gar keine Möglichkeit mehr, lange Inhalte in einem Storyboard zu erfassen (nicht mal in mehreren Sections wie es in eCamp2 möglich war). Ich sehe das als eine Regression, was findest du?

2022-05-08 05:48 UTC, usu commented
> Sieht visuell sehr gut aus, aber jetzt können lange Storyboards gar nicht mehr über mehrere Seiten umbrechen.

Sections brechen bei mir in Tabellen-Layout um (siehe angehängtes PDF). Mit schönem Layout natürlich nur mit Chrome schön, mit PagedJS noch distorted.
[Harry-Potter-Lager (10).pdf](https://github.com/ecamp/ecamp3/files/8646400/Harry-Potter-Lager.10.pdf)

Hat bei dir nicht funktioniert?

2022-05-10 10:13 UTC, carlobeltrame commented
Bei mir funktionierts nicht ganz so gut, nein. Ich teste mit dem GRGR-Lager, und drucke jeweils das ganze Lager mit den Standardeinstellungen. Die Issues sind zum Beispiel beim Block 2.6 sichtbar.

In der Preview wird die Tabelle nicht umgebrochen:
![Screenshot from 2022-05-10 12-07-23](https://user-images.githubusercontent.com/7566995/167605388-81ea79af-e881-49e8-985d-7dc5cfcc66b6.png)

Das Puppeteer-PDF sieht dann ganz anders aus, was mich schon mal besorgt. Der Block 2.6 bricht zwar um, aber das Problem mit den verschwundenen Spalten ist immer noch da (siehe im PDF die Seite 9):
[GRGR-2654.pdf](https://github.com/ecamp/ecamp3/files/8660608/GRGR-2654.pdf)

2022-05-10 12:36 UTC, usu commented
> In der Preview wird die Tabelle nicht umgebrochen:

Preview funktioniert mit PagedJS und dort funktioniert das Layout sowohl mit flex als auch mit table nicht. Die Chance, dass table gefixt wird ist aber grösser (laut den Entwicklern wird dort aktiv daran gearbeitet).

> Das Puppeteer-PDF sieht dann ganz anders aus, was mich schon mal besorgt

Tailwind-Issue, gefixt mit https://github.com/ecamp/ecamp3/pull/2652. In diesem Druck ist Tailwind-CSS nicht geladen.

Ich habe devel gemerged damit beide #2652 und #2653 drin sind. GRGR-Lager sieht bei mir gedruckt so aus wie angehängt:
[GRGR (2).pdf](https://github.com/ecamp/ecamp3/files/8661508/GRGR.2.pdf)

2022-05-11 15:09 UTC, carlobeltrame approved these changes
Sieht gut aus jetzt, merci!

2022-05-11 15:09 UTC, merged