Chore/dashboard performance
ecamp/ecamp3 pull request #2763
Opened 2022-05-28 05:41 UTC by usu

Had to base this on #2683 

Improves performance of dashboard view. Limits to 3 network calls instead if individual calls to each activity and each scheduleEntry.

A potential improvement could be to only load activities from API which I'm responsible for. However, impact is not large. And as an additional benefit, all data is already loaded if I switch to the picasso afterwards.

`day.scheduleEntries()` is now calcuated in memory, similar as in print:
https://github.com/ecamp/ecamp3/blob/devel/print/components/ProgramDay.vue#L36

This relation might also benefit, if we return individual scheduleEntry links instead of 1 single collection link (similar as contentNode->children). 
@carlobeltrame: What do you think on this?

2022-05-29 13:01 UTC, manuelmeister requested changes

2022-05-29 13:01 UTC, manuelmeister commented on frontend/src/views/camp/Dashboard.vue
> +                    <template v-for="scheduleEntry in scheduleEntriesByDay(day)">
Can this be cached? I thought this would loop, as it is not a computed property.

2022-06-09 19:27 UTC, BacLuc approved these changes

2022-06-11 11:11 UTC, usu commented on frontend/src/views/camp/Dashboard.vue
> +                    <template v-for="scheduleEntry in scheduleEntriesByDay(day)">
I don't think this method is very expensive, but didn't do a deeper analysis. Any good proposal on how to cache?

2022-06-12 19:42 UTC, manuelmeister commented on frontend/src/views/camp/Dashboard.vue
> +                    <template v-for="scheduleEntry in scheduleEntriesByDay(day)">
Wouldn't this be better with a computed property? Or am I missing something?

2022-06-13 21:40 UTC, manuelmeister approved these changes
Nice
Minor: use reduce

2022-06-13 21:42 UTC, pmattmann approved these changes

2022-06-13 21:45 UTC, merged