Feature: change mail-adress
ecamp/ecamp3 pull request #2800
Opened 2022-06-06 12:37 UTC by pmattmann

Bietet Funktionalität zum Ändern der eigenen Mail-Adresse

2022-06-07 19:55 UTC, BacLuc commented on api/src/Entity/Profile.php
> +     * If set, a verification-mail is set to this email-adress.
```suggestion
     * If set, a verification-mail is sent to this email-address.
```

2022-06-07 22:08 UTC, carlobeltrame requested changes

2022-06-07 22:08 UTC, carlobeltrame commented on api/src/DataPersister/ProfileDataPersister.php
> +    public function beforeUpdate($data): BaseEntity {
Wie siehts im create-Fall aus? Kann ich da einfach eine beliebige Mailadresse setzen und die ist dann automatisch trusted? Wenn nein, wird ein Verifikations-Mail versendet?

2022-06-07 22:08 UTC, carlobeltrame commented on api/src/Entity/Profile.php
> +    #[Groups(['write'])]
Das könnte man vermutlich auf `'update'` reduzieren. Bin zwar gerade nicht sicher wo wir die Groups `'create'` und `'update'` definieren, aber `'create'` ist bereits weiter oben im Einsatz.

2022-06-07 22:08 UTC, carlobeltrame commented on api/src/Entity/Profile.php
> +    #[Assert\DisableAutoMapping]
Brauchts das wirklich? Welche Auto-Validierung schaltest du damit aus?

2022-06-07 22:08 UTC, carlobeltrame commented on api/src/Entity/Profile.php
> +     * If set, a verification-mail is set to this email-adress.
```suggestion
     * If set, a verification email is sent to this email address.
```

2022-06-07 22:08 UTC, carlobeltrame commented on api/src/Entity/Profile.php
> +     * Will become the email when it is verified by a Link send to the adress.
```suggestion
     * Will become the email when it is verified by a link sent to the adress.
```

2022-06-07 22:08 UTC, carlobeltrame commented on api/src/Entity/Profile.php
> +     * User-Input for email verification.
```suggestion
     * User input for email verification.
```

2022-06-07 22:08 UTC, carlobeltrame commented on api/src/Service/MailService.php
> +            ->subject('eCamp3 :: Verify E-Mail-Adress')
Das Subject zu übersetzen müssten wir uns auch irgendwann mal überlegen

2022-06-07 22:08 UTC, carlobeltrame commented on api/templates/emails/verifyMailAdress.de.html.twig
> +    Deine Mail-Adresse bei eCamp soll geändert werden.
```suggestion
    Jemand hat versucht, deine Mail-Adresse bei eCamp zu ändern.
```

2022-06-07 22:08 UTC, carlobeltrame commented on api/templates/emails/verifyMailAdress.de.html.twig
> +    Bestätige deine neue Mail-Adressse indem du den nachfolgenden Link öffnest:
```suggestion
    Falls du das warst, bestätige deine neue Mail-Adressse indem du den nachfolgenden Link öffnest:
```

2022-06-07 22:08 UTC, carlobeltrame commented on api/templates/emails/verifyMailAdress.de.text.twig
> +Deine Mail-Adresse bei eCamp soll geändert werden.
```suggestion
Jemand hat versucht, deine Mail-Adresse bei eCamp zu ändern.
```

2022-06-07 22:08 UTC, carlobeltrame commented on api/templates/emails/verifyMailAdress.de.text.twig
> +Bestätige deine neue Mail-Adressse indem du den nachfolgenden Link öffnest:
```suggestion
Falls du das warst, bestätige deine neue Mail-Adressse indem du den nachfolgenden Link öffnest:
```

2022-06-07 22:08 UTC, carlobeltrame commented on api/templates/emails/verifyMailAdress.de.html.twig
> +    Neue Mail-Adresse:  {{ newMail }}
Escaped Twig diese Strings von selber? Standardmässig verwendet Symfony beim Email-Validator folgenden Regex: `/^.+\@\S+\.\S+$/`
Zwar kann aktuell das Profil nur jeder von sich selber ändern. Ich würde aber trotzdem durchgängig in allen Mails alle Datenbank-Werte escapen. Sonst kann ich z.B. via meinen Usernamen (oder hier via die newMail) Script-Tags in Mails einbauen, welche eCamp an beliebige User sendet deren ID ich kenne.

2022-06-07 22:08 UTC, carlobeltrame commented on api/templates/emails/verifyMailAdress.en.html.twig
> +    Old Mail-Adresse:  {{ oldMail }}
```suggestion
    Old email address:  {{ oldMail }} 
```

2022-06-07 22:08 UTC, carlobeltrame commented on api/templates/emails/verifyMailAdress.en.html.twig
> +    New Mail-Adresse:  {{ newMail }}
```suggestion
    New email address:  {{ newMail }} 
```

2022-06-07 22:08 UTC, carlobeltrame commented on api/templates/emails/verifyMailAdress.en.html.twig
> +    Your Mail-Adresse on eCamp3 will be changed.
```suggestion
    Someone requested to change your email address on eCamp.
```

2022-06-07 22:08 UTC, carlobeltrame commented on api/templates/emails/verifyMailAdress.en.html.twig
> +    Please confirm:
```suggestion
    If that was you, please confirm by clicking this link:
```

2022-06-07 22:08 UTC, carlobeltrame commented on api/templates/emails/verifyMailAdress.en.text.twig
> +Your Mail-Adresse on eCamp3 will be changed.
```suggestion
Someone requested to change your email address on eCamp.
```

2022-06-07 22:08 UTC, carlobeltrame commented on api/templates/emails/verifyMailAdress.en.text.twig
> +Please confirm:
```suggestion
If that was you, please confirm by clicking this link:
```

2022-06-07 22:08 UTC, carlobeltrame commented on api/templates/emails/verifyMailAdress.en.text.twig
> +Old Mail-Adresse:  {{ oldMail }}
```suggestion
Old email address:  {{ oldMail }} 
```

2022-06-07 22:08 UTC, carlobeltrame commented on api/templates/emails/verifyMailAdress.en.text.twig
> +New Mail-Adresse:  {{ newMail }}
```suggestion
New email address:  {{ newMail }} 
```

2022-06-07 22:08 UTC, carlobeltrame commented on frontend/src/views/Profile.vue
> +                    Change
Use a translation please :)

2022-06-07 22:08 UTC, carlobeltrame commented on frontend/src/components/user/DialogChangeMail.vue
> +    :cancel-label="'Close'"
Use a translation please :)

2022-06-07 22:08 UTC, carlobeltrame commented on frontend/src/components/user/DialogChangeMailRunning.vue
> +    :cancel-label="'Close'"
Use a translation please :)

2022-06-07 22:08 UTC, carlobeltrame commented on frontend/src/views/Profile.vue
> +    <dialog-change-mail-running :email-verification-key="emailVerificationKey" />
I don't understand why you use two dialogs at all. I see no way to ever activate the `dialog-change-mail-running`, and the `dialog-change-mail` does a good job of showing the progress and completion status of the email change. Couldn't you remove this second dialog completely?

2022-06-07 22:08 UTC, carlobeltrame commented on frontend/src/components/user/DialogChangeMail.vue
> +      {{ $tc('components.user.dialogChangeMail.success') }}
The other dialog promises some nice spinners and icons. Could you transfer those to this dialog?

2022-06-09 19:36 UTC, BacLuc commented on api/src/DataPersister/ProfileDataPersister.php
> +    public function beforeUpdate($data): BaseEntity {
Da geht es über den activationKeyHash vom User.
Wir brauchen 2 mechanismen. Wenn man die email ändert, soll man ja nicht plötzlich nicht mehr aktiviert sein.

2022-06-09 19:48 UTC, BacLuc reviewed
Cool, even works when you are not logged in and click on the link.
You can log in, and then you are redirected to the profile page with the spinner

2022-06-09 19:48 UTC, BacLuc commented on frontend/src/components/user/DialogChangeMail.vue
> +    :submit-action="(status == 'initial') ? sendChangeMailRequest : null"
===

2022-06-09 19:48 UTC, BacLuc commented on frontend/src/components/user/DialogChangeMail.vue
> +    :cancel-action="(status == 'initial') ? null : close"
===

2022-06-09 19:48 UTC, BacLuc commented on frontend/src/components/user/DialogChangeMail.vue
> +  <dialog-form
maybe this is a problem with dialog-form, but you cannot close the dialog with the x if there is no email

2022-06-09 19:49 UTC, BacLuc commented on frontend/src/components/user/DialogChangeMail.vue
> +      {{ $tc('components.user.dialogChangeMail.success') }}
I would add a hint here that you have to verify the new email address, before you can use it

2022-06-11 12:36 UTC, usu requested changes
Nice. Tested and works well for me. Small changes as per proposals below.

2022-06-11 12:36 UTC, usu commented on frontend/src/views/Profile.vue
> +                :editing="false"
```suggestion
                disabled
```

`editing` property existiert nicht auf `ApiTextField`

2022-06-11 12:36 UTC, usu commented on frontend/src/locales/en.json
> +        "title": "Change Mail-Adress",
```suggestion
        "title": "Change email address",
```

2022-06-11 12:36 UTC, usu commented on frontend/src/locales/en.json
> +        "message": "You will receive a mail for verification.",
```suggestion
        "message": "You will receive an email for verification.",
```

2022-06-11 12:36 UTC, usu commented on frontend/src/locales/en.json
> +        "success": "Before you can use your new mail address, you have to verify it. Check your mailbox now.",
```suggestion
        "success": "Before you can use your new email address, you have to verify it. Check your mailbox now.",
```

2022-06-11 12:36 UTC, usu commented on frontend/src/locales/en.json
> +        "title": "Changing Mail-Adress",
```suggestion
        "title": "Changing email address",
```

2022-06-11 12:36 UTC, usu commented on frontend/src/locales/en.json
> +        "message": "Changing Mail-Adresse ...",
```suggestion
        "message": "Changing email address...",
```

2022-06-11 12:36 UTC, usu commented on frontend/src/locales/en.json
> +        "success": "Mail-Adresse successfully changed.",
```suggestion
        "success": "Email address successfully changed.",
```

2022-06-11 21:08 UTC, pmattmann commented on frontend/src/views/Profile.vue
> +                :editing="false"
ich hab 'readonly' gewählt. 
bei 'disabled' wird die Farbe vom Control anders - was seltsam ausseiht.

2022-06-11 21:17 UTC, pmattmann commented on api/templates/emails/verifyMailAdress.de.html.twig
> +    Neue Mail-Adresse:  {{ newMail }}
Bei Twig ist Escaping von Variabeln im Template der Standard (https://twig.symfony.com/doc/3.x/templates.html#html-escaping)

2022-06-12 05:47 UTC, usu approved these changes

2022-06-13 07:55 UTC, carlobeltrame commented
Noch zwei Szenarien die man noch testen müsste:
- Ich erstelle mir einen neuen Account, aktiviere ihn noch nicht. Dann ändere ich (von mir aus via API wenn ich im Frontend nicht die Möglichkeit bekomme) meine Mailadresse. Komme ich dadurch in irgendeinen speziellen Zustand? Kann ich danach etwas was ich nicht können sollte? Kann ich etwas nicht, was ich können sollte?
- Ich registriere mich via OAuth, und ändere dann meine Mailadresse. Funktioniert der OAuth Login danach noch? Passiert sonst etwas unerwartetes?

2022-06-13 09:09 UTC, BacLuc commented
You maybe have conflicts now with merged https://github.com/ecamp/ecamp3/pull/2769

2022-06-13 19:06 UTC, carlobeltrame approved these changes
Wenn der Mail-Change bei OAuth keine unerwarteten Faxen macht ist gut für mich, merci! :+1:

2022-06-13 20:55 UTC, merged