Zf3.feature/module api
ecamp/ecamp3 pull request #301
Opened 2018-11-03 11:21 UTC by pmattmann

2018-12-03 14:04 UTC, carlobeltrame requested changes

2018-12-03 14:04 UTC, carlobeltrame commented on module/eCampApi/config/autoload/camp.config.php
> +            'collection_query_whitelist' => [ 'owner_id', 'user_id', 'creator_id' ],
These queries don't work so far, so why add them to the whitelist? I am testing manually with URL `/api/camp?creator_id=<some-nonexistent-userid>` and still get all camps returned

2018-12-03 14:04 UTC, carlobeltrame commented on module/eCampApi/config/autoload/camp.config.php
> +            'collection_query_whitelist' => [ 'owner_id', 'user_id', 'creator_id' ],
The added tests check if the entity is returned, but don't check if all unmatched entities are omitted.

2018-12-03 14:04 UTC, carlobeltrame commented on module/eCampApi/config/module.config.php
> +                    'route' => '/api-docu[/:action]',
Even when I am logged in to my local API server, when using the Try it out feature of Swagger on the camps collection (`GET /api/camps`), I get status 403. Is this possibly an issue of petstore.swagger.io not setting the withCredentials flag on its XmlHTTPRequests (AKA fetch call)? The session cookie is not sent along with the generated API call.

2018-12-03 14:04 UTC, carlobeltrame commented on module/eCampApi/src/Controller/SwaggerController.php
> +        header('Access-Control-Allow-Origin: *');
This should be handled by the AcaoInjector, or later by ZfrCors, right? If so, remove this line

2018-12-03 14:04 UTC, carlobeltrame commented on module/eCampCore/data/prod/CampTypeData.php
> +            $campType->setJsonConfig(json_encode([
Consider extracting this duplicated code into a method.

2018-12-03 14:04 UTC, carlobeltrame commented on module/eCampCore/data/prod/CampTypeData.php
> +            $campType->setJsonConfig(json_encode([
Duplicated here.

2018-12-03 14:04 UTC, carlobeltrame commented on module/eCampCore/src/Acl/CampAcl.php
> +                return true;
Is this temporary? This creates dead code below. Also consider replacing `return false || (...) || (...)` expression with the same form as in UserAcl.php (`return (...) || (...)`). Or replace it there, just be consistent.

2018-12-03 14:04 UTC, carlobeltrame commented on module/eCampCore/src/Entity/Day.php
> +    public function getEventInstances() {
Please add a unit test for this relatively complicated mathematical expression. Current tests only check the number of results, not the contents of the results.

2018-12-03 14:04 UTC, carlobeltrame commented on module/eCampCore/src/EntityService/AbstractEntityService.php
> +    protected function getOrigEntityData($entity) {
How did the call of this method in PeriodService.php:146 work before this PR?

2018-12-03 14:04 UTC, carlobeltrame commented on module/eCampCore/src/EntityService/AbstractEntityService.php
> +        $primaryKey = $this->serviceUtils->emGetPrimaryKeyColumn($className);
How does this work in case we have composite primary keys (e.g. in join tables)?

2018-12-03 14:04 UTC, carlobeltrame commented on module/eCampCore/src/EntityService/AbstractEntityService.php
> +        $q->andWhere($alias . '.' . $primaryKey . ' = :entity_id');
Should `$alias` and `$primaryKey` be escaped / quoted based on the DBMS?

2020-02-14 16:36 UTC, manuelmeister commented
Was ist mit diesem Pull Request? @carlobeltrame @pmattmann ?

2020-02-14 17:28 UTC, carlobeltrame commented
Ist veraltet, @pmattmann wollte aber mal noch schauen ob da noch etwas nützliches drin ist das man behalten müsste.

2020-02-29 23:57 UTC, closed without merging