Improve print ui
ecamp/ecamp3 pull request #3182
Opened 2022-11-20 19:03 UTC by manuelmeister

before:
![Bildschirmfoto 2022-11-20 um 20 02 20](https://user-images.githubusercontent.com/3001985/202920776-205e2058-6af6-4bb8-b1e8-0370a61a0afb.png)

after:
![Bildschirmfoto 2022-11-20 um 19 58 58](https://user-images.githubusercontent.com/3001985/202920740-51d82048-0a19-4489-9657-a01787037da8.png)
![Bildschirmfoto 2022-11-20 um 19 59 15](https://user-images.githubusercontent.com/3001985/202920738-510618e0-80b5-4778-b28f-08c45425164f.png)

2022-12-19 17:31 UTC, pmattmann approved these changes
I like it :)

2022-12-19 17:34 UTC, pmattmann commented
Ich habe mir nur eine Frage gestellt.
Müssen wir den Hintergrund künstlich ausgrauen, damit man die Papiere erkennt.
Aus Neugier habe ich versucht Alternativen versucht.

![image](https://user-images.githubusercontent.com/470237/208485421-cb3bab83-6b4e-4415-9763-4307f50a1d0e.png)

2022-12-19 17:34 UTC, pmattmann commented
![image](https://user-images.githubusercontent.com/470237/208485786-2c3af8f0-e622-4f8b-ae14-8833b554e3db.png)

2022-12-20 07:59 UTC, manuelmeister commented
Ja so etwas könnten wir noch in einem nächsten PR anschauen 👍

Finde es nicht schlecht, noch einmal zu überdenken, ob ein grauer Hintergrund Sinn ergibt oder lieber graue/farbige Seiten.

2023-01-17 14:16 UTC, BacLuc requested changes
I tested it quickly and had the following findings:
- If you change the order of the pages with drag and drop
  - this is not reflected in the print config for the developer (minor), but may be related to the other two effects
  - nuxt print does not respect the order
  - react print does not respect the order
Am i right that this is just not implemented?
It works on the devel branch

Deleting and adding content works fine

Some other minor things

2023-01-17 14:16 UTC, BacLuc commented on frontend/src/components/print/config/ProgramConfig.vue
> +    multiple: true,
minor:
polymorphism is cool, but i don't know if 5 times a false makes it worth.
I don't have a better idea right  now (except for a "default implementation" with false.

2023-01-17 14:16 UTC, BacLuc commented on frontend/src/components/print/configurator/PagesConfig.vue
> +    cursor: -webkit-grab;
do we still need these browser specific values?

2023-01-17 14:16 UTC, BacLuc commented on frontend/src/components/print/configurator/PagesConfig.vue
> +  min-width: 48px !important;
do we need the important here

2023-01-17 14:16 UTC, BacLuc commented on frontend/src/components/print/configurator/PagesConfig.vue
> +  color: map-get($red, 'base') !important;
do we need the important here

2023-01-17 21:37 UTC, BacLuc commented
If you want to deploy this branch, you should pull devel into it.
the build and deploy fails because we still reference an unsupported postgres helm chart.
There is a temporary fix on devel.

2023-01-24 21:37 UTC, BacLuc approved these changes

2023-01-24 22:14 UTC, merged