bugfix/Camp: allow to edit camp when it was created with a coupon
ecamp/ecamp3 pull request #3265
Opened 2023-02-14 11:23 UTC by BacLuc

Bug was detected because no CampCollaboration could be created for a camp with a couponKey.
- Add a camp with couponkey to camps.yml that we detect if a similar bug happens
- Only run the validator on Camp:create
- Remove the couponKey from the data when creating a Camp if the feature is deactivated, because there is a unique constraint.
(null does not match with the = operator)

2023-02-22 10:25 UTC, carlobeltrame approved these changes

2023-02-24 17:22 UTC, usu requested changes

2023-02-24 17:22 UTC, usu commented on api/src/Service/CampCouponService.php
> +    public function isActive(): bool {
Shouldn't that be named `isDisabled`?

Or keep the name, but then the return value would need to be  `return '' !== $this->secret;`

2023-02-24 17:22 UTC, usu commented on api/src/State/CampCreateProcessor.php
> +            $data->couponKey = null;
Why this? This now allows someone to use the same code multiple times.

2023-02-24 19:46 UTC, usu approved these changes

2023-02-24 19:46 UTC, merged