EntityLink
ecamp/ecamp3 pull request #335
Opened 2019-09-18 13:27 UTC by pmattmann

2019-09-18 13:28 UTC, pmattmann commented on backend/module/eCampCore/src/Hydrator/CampHydrator.php
> +            'creator' => new EntityLink($camp->getCreator()),
Beispiel für Entity-Referenc: new EntityLink(...)

2019-09-18 20:03 UTC, carlobeltrame requested changes

2019-09-18 20:03 UTC, carlobeltrame commented on frontend/.env.development
> +VUE_APP_ROOT_API=http://localhost:8888/api
Bitte diese Datei aus git entfernen und .env.development zu .gitignore hinzufügen :) beim Docker-setup übersteuert .env.development wie es scheint .env.local

2019-09-18 20:03 UTC, carlobeltrame commented on backend/module/eCampCore/src/Hydrator/CampHydrator.php
> +            'creator' => new EntityLink($camp->getCreator()),
Funktioniert soweit, merci :) frontend liest dies korrekt als Link und merkt sich im camp die URI vom creator, lädt ihn aber erst wenn er explizit aufgerufen wird (z.B. via `{{ campDetails.creator().username }}` in einer view)

2019-09-18 22:06 UTC, pmattmann commented on backend/module/eCampCore/src/Hydrator/CampHydrator.php
> +            'creator' => EntityLink::Create($camp->getCreator()),
EntityLink::Create ist stabil gegen NULL

2019-09-19 08:31 UTC, carlobeltrame approved these changes

2019-09-19 08:35 UTC, merged