Feature/store.del
ecamp/ecamp3 pull request #336
Opened 2019-10-05 10:29 UTC by pmattmann

2019-10-09 20:23 UTC, carlobeltrame requested changes
Cool! Ich habe das so bei mir getestet und es sind mir folgende Dinge aufgefallen:
* delete camp-collaboration funktioniert im backend, aber delete camp immer noch nicht, da gibts constraint violations (ist vielleicht auch gut so). Jedenfalls bekomme ich dabei einen HTTP-Status 200 ohne CORS-Headers zurück, obwohl Zend intern vor dem commit die richtige 204er-response bereit hat.
* Ich verstehe nicht ganz, wofür der STATUS_UNRELATED auf einer campCollaboration gut sein soll, ist das nur damit du patch testen konntest? Wenn ja könnte man das ja wieder durch delete ersetzen, da patch auch für die anderen Status-Mutationen angewendet wird
* Ich habe mit zwei Varianten für delete im Store herumgespielt, und ich glaube inzwischen, es braucht beide, denn keine der beiden ist eine komplette Lösung:
  * Deine Lösung, das _meta.deleted flag zu setzen ist elegant, aber z.B. stimmt bei paginated lists die das gelöschte Objekt enthalten die Anzahl Elemente nicht.
  * Stattdessen kann man auch den Store nach allen Objekten durchsuchen, die das gelöschte Objekt referenzieren, und diese Objekte neu von der API laden. Das habe ich schon implementiert, aber es hat auch seine Probleme: Sagen wir ich lösche eine camp-collaboration aus einem camp, also muss das camp neu aus der API geladen werden. Bis dieses Resultat da ist, kennt der reaktive Frontend-Code aber immer noch nur das alte Camp und hat das Gefühl, da sei die collaboration drin. Da wir wohl gerade noch in einer Ansicht sind die die collaborations anzeigt, wird automatisch versucht, die schon gelöschte camp-collaboration aus der API zu laden. Dies führt zu unnötigen Requests mit Response 404.

Ich werde mich in nächster Zeit wohl damit beschäftigen, diese beiden Ideen zu kombinieren.

2019-10-10 18:42 UTC, pmattmann commented
Ja, das Löschen verträgt sich mit dem den Paginated-Listen nicht so gut, seh ich auch so.
Dabei spielt es wohl nicht einmal so eine grosse Rolle, ob man eine Element aus der Liste selber löscht, oder ob es jemand anderes tut... 
Müssen wir unbedingt noch einmal besprechen.

2019-11-11 20:09 UTC, pmattmann commented
Ablauf beim Löschen:
1. Deleting markieren
2. API Delete-Call (Bei API-Error: Deleting zurücksetzen; break)
3. FindAllItemReferencing -> reload all ( promise.all() )
4. Item aus Store entfernen (purge)

Tipp:
Deleting kann am UI verwendet werden. ZB für sofortiges ausblenden, oder für ausgrauen...

2019-11-11 21:47 UTC, pmattmann commented
`
// V1:
// Verboten:
// /api/day

// /api/day?camp_id=1                       -> liefert alle
// /api/day?camp_id=1&page_size=10&page=1   -> liefert Seite 1
// /api/day?camp_id=1&page_size=10&page=2   -> liefert Seite 2


// Löschen von Item in Store:
// 1. Deleting markieren
// 2. API Delete-Call (Bei API-Error: Deleting zurücksetzen; break)
// 3. FindAllItemReferencing -> reload all ( promise.all() )
// 3.1) Collections im Store mit Item als Element                     { _embedded: { items: [ <>, ... ] } }
// 3.2) Objects im Store mit Sub-Collection mit Item als Element      { _embedded: { periods: [ <>, ... ] } }
// 3.3) Objects im Store mit Reference auf Item                       { _embedded: { period: <> } }
// 4. Item aus Store entfernen (purge)
`

2019-12-16 19:14 UTC, closed without merging