Vuetify proof of concept
ecamp/ecamp3 pull request #351
Opened 2020-01-03 07:37 UTC by usu

Nicht zum mergen. Lediglich als Anschauungsobjekt für #344 

Das Frontend müsste grundsätzlich funktionieren, allerdings noch nicht vollständig optimiert für Mobile.

Nicht gemacht sind alle Authentifizierungs/Registrierungs-Ansichten. Das würde ich dann nach einem allfälligen Entscheid migrieren.

2020-01-03 14:43 UTC, carlobeltrame reviewed
Sieht eigentlich ganz gut aus! Wirkt tatsächlich moderner muss ich zugeben.

2020-01-03 14:43 UTC, carlobeltrame commented on frontend/package.json
> +    "@mdi/font": "^4.7.95",
Müssten Fonts wie @mdi/font und typeface-roboto nicht auch in dependencies statt devDependencies sein? Falls sie automatisch ins production bundle aufgenommen werden, ist das nicht auch mit Vuetify und sogar Vue selber der Fall? Oder ist das vorgedacht für wenn die Fonts vom CDN kommen?

2020-01-03 14:43 UTC, carlobeltrame commented on frontend/src/plugins/vuetify.js
> +import Vue from 'vue';
```suggestion
import Vue from 'vue'
```

2020-01-03 14:43 UTC, carlobeltrame commented on frontend/src/plugins/vuetify.js
> +import Vuetify from 'vuetify/lib';
```suggestion
import Vuetify from 'vuetify/lib'
```

2020-01-03 14:43 UTC, carlobeltrame commented on frontend/src/plugins/vuetify.js
> +Vue.use(Vuetify);
```suggestion
Vue.use(Vuetify)
```

2020-01-03 14:43 UTC, carlobeltrame commented on frontend/src/plugins/vuetify.js
> +});
```suggestion
})
```
Fix linter errors

2020-01-03 15:22 UTC, usu commented on frontend/package.json
> +    "@mdi/font": "^4.7.95",
Ja, das war die Idee dahinter. Als packages für development und CDN für production. Aber ehrlich gesagt ist diese Überlegung eh viel zu früh (premature optimiziation). Ich nehm sie in die normalen dependencies, über CDN können wir uns sorgen machen, wenn wir dann wirklich ein Performance-Problem feststellen.

2020-01-24 22:06 UTC, manuelmeister requested changes
### Meeting Review
Please fix merge conflicts

2020-01-27 16:12 UTC, merged