Feature/configurable hydrators
ecamp/ecamp3 pull request #357
Opened 2020-01-25 14:24 UTC by pmattmann

Basiert auf PR #351

2020-01-26 17:31 UTC, manuelmeister approved these changes

2020-01-26 17:31 UTC, manuelmeister commented on frontend/src/views/auth/Login.vue
> -          <PbsMiDataLogo />
Da ist wohl ein ein Fehler unterlaufen. Wieso wurde das gelöscht?

2020-01-27 17:36 UTC, pmattmann commented on frontend/src/views/auth/Login.vue
> -          <PbsMiDataLogo />
Thx - ist korrigiert

2020-01-27 23:01 UTC, manuelmeister approved these changes

2020-01-28 20:13 UTC, usu requested changes

2020-01-28 20:13 UTC, usu commented on backend/module/eCampApi/config/module.config.php
> +//                'hydrator' => \eCamp\Core\Hydrator\CampHydrator2::class
Kann man löschen, oder?

2020-01-28 20:13 UTC, usu commented on backend/module/eCampCore/src/Hydrator/CampCollaborationHydrator.php
> +            'camp' => EntityLink::Create($campCollaboration->getCamp()),
Machst du das bewusst, `camp` und `user` nur als Link einzubinden anstatt als eingebettete Ressource? So sind viel mehr Netzwerkaufrufe notwendig um an die Daten zu kommen. Für die Collaborator-Seite machst du jetzt pro User 2 Aufrufe, bei 10 Leitern sind das 20 Netzwerkaufrufe. Besser wäre, alles mit einem einzigen Netzwerkaufruf abzuwischen (api/camp-collaborations?camp_id=123).

Siehe Beispiel hier:
https://github.com/ecamp/ecamp3/blob/c953ba6de2c490d0da92fc5dbe42886baa29e7d0/backend/module/eCampCore/src/Hydrator/CampHydrator.php#L37

und hier:
https://github.com/ecamp/ecamp3/blob/c953ba6de2c490d0da92fc5dbe42886baa29e7d0/frontend/src/components/camp/Picasso.vue#L72

2020-01-28 20:13 UTC, usu commented on backend/module/eCampCore/src/Hydrator/CampHydrator.php
> +//            'owner' => EntityLink::Create($camp->getOwner()),
Per heute gibt es immer noch einen Owner im Datenmodell, muss jetzt einfach ein User sein (keine Gruppe). Wollen wir den ganz abschaffen?

2020-01-28 20:13 UTC, usu commented on backend/module/eCampCore/src/Hydrator/CampHydrator.php
> +            'events' => new EntityLinkCollection($camp->getEvents()),
Du hast mir den Event-Link geklaut :-)
Siehe Beispiel weiter oben --> mein bisheriger "Picasso" basiert darauf, dass er unter einem Endpunkt alle Events (und Instanzen) eines Lagers laden kann. Aus einem Netzwerkaufruf um den Picasso anzuzeigen werden jetzt ganz viele.

2020-01-28 20:13 UTC, usu commented on backend/module/eCampCore/src/Hydrator/EventTypeFactoryHydrator.php
>  class EventTypeFactoryHydrator implements HydratorInterface {
Was macht die EventTypeFactory schon wieder? 
Fehlt irgendwie noch in meiner Doku:
https://github.com/ecamp/ecamp3/wiki/4-domain-object-model

2020-01-28 20:13 UTC, usu commented on backend/module/eCampCore/src/Hydrator/CampCollaborationHydrator.php
> +            'camp' => EntityLink::Create($campCollaboration->getCamp()),
Ah, jetzt versteh ich. Man müsste HydrateInfo entsprechend konfigurieren. Kann man für Collections und einzelne Entitites unterschiedlich konfigurieren oder ist das dieselbe? Wenn Zweiteres, dann würd ich vorschlagen sicher den user (evt. auch camp) als embedded aufzunehmen.

2020-01-29 17:06 UTC, pmattmann commented on backend/module/eCampApi/config/module.config.php
> +//                'hydrator' => \eCamp\Core\Hydrator\CampHydrator2::class
stimmt

2020-01-29 17:08 UTC, pmattmann commented on backend/module/eCampCore/src/Hydrator/CampCollaborationHydrator.php
> +            'camp' => EntityLink::Create($campCollaboration->getCamp()),
HydrateInfo ist aktuell für Entity und Collection dieselbe.
Include von User und Camp ist für mich OK.

2020-01-29 17:14 UTC, pmattmann commented on backend/module/eCampCore/src/Hydrator/CampHydrator.php
> +            'events' => new EntityLinkCollection($camp->getEvents()),
Spannender Punkt!

Bei den Entitäten ist es so, dass es eigentlich egal ist, ob diese als Referenz oder als Embedded mitgegeben wird. Falls es eine Referenz ist, wird diese vom Store automatisch nachgeladen.
Man darf daher (nahe zu) nach belieben eine Referenz in eine Entität umbauen - und umgekehrt...

Bei "Embedded Collections" vs. "Link auf einen gefilterten Endpoint" gilt diese Austauschbarkeit leider nicht. Müssten wir das haben? 

Müssen wir evtl. nächstes mal besprechen.

2020-01-29 17:33 UTC, pmattmann commented on backend/module/eCampCore/src/Hydrator/EventTypeFactoryHydrator.php
>  class EventTypeFactoryHydrator implements HydratorInterface {
Ist noch etwas entfernt.
Idee war, dass eine EventTypeFactory für ein EventType ein neues Event erstellt und dieses konfiguriert (gewünschte Plugins hinzufügt).
z.B.
- LS SportBlock    (3 teiligkeit, ...)
- LS Wanderung   (MZB, ...)

2020-01-29 18:25 UTC, pmattmann commented on backend/module/eCampCore/src/Hydrator/CampHydrator.php
> +            'events' => new EntityLinkCollection($camp->getEvents()),
Issue erfasst

2020-01-29 18:28 UTC, pmattmann commented
@usu:
Bitte zusammenführen - falls soweit ok.
Für Diskussion "Embedded Collection" vs. Link auf "Filtered Endpoint" habe ich ein Issue (Meeting Discuss) erfasst.

2020-02-09 13:04 UTC, merged

2020-02-17 17:52 UTC, manuelmeister commented on backend/module/eCampCore/src/Hydrator/CampHydrator.php
> +//            'owner' => EntityLink::Create($camp->getOwner()),
Meeting Note: Wird wieder eingefügt #370