Migration zu vuetify
ecamp/ecamp3 pull request #358
Opened 2020-01-27 23:06 UTC by manuelmeister

Jetzt sollte alles in seinem aktuellen Gewand migriert sein. Es gibt einige Dinge die im Moment nur gemockt sind und nicht wirklich so funktionieren. Schauts euch einmal an.

Fixes #344

2020-01-28 14:47 UTC, carlobeltrame requested changes
Merci!

2020-01-28 14:47 UTC, carlobeltrame commented on frontend/src/App.vue
> -  @import '../node_modules/typeface-roboto/index.css';
Ich stimme hier nicht ganz zu. Für mich geht ein beträchtlicher Teil der Eleganz und des modernen Feels verloren wenn das UI in Arial gerendert wird (nicht alle Benutzer haben einen Mac mit Helvetica). Es muss von mir aus nicht zwingend Roboto sein, kann auch Open Sans, Source Sans Pro, Noto Sans sein.

Falls ich überstimmt werde und wir die Font trotzdem nicht reinnehmen wollen, müsste man Roboto noch aus den Dependencies und aus frontend/public/index.html nehmen.

2020-01-28 14:47 UTC, carlobeltrame commented on frontend/src/views/auth/Login.vue
> +  </v-content>
Cool dass das mal im Material Design ist, ganz überzeugt vom aussehen dieser Seite bin ich aber noch nicht. Aber für die Migration passts mal im Moment.

2020-01-28 14:47 UTC, carlobeltrame commented on frontend/src/components/camp/Picasso.vue
> +      type="table-thead,table-row@6" />
Die Margins dieses skeleton-loaders könnte man noch etwas verschönern, er klebt momentan etwas weit oben und ganz am linken Rand.

2020-01-28 14:47 UTC, carlobeltrame commented on backend/module/eCampCore/data/dev/EventCategoryData.php
> +            $eventCategory->setColor('#8bc34a');
Könntest du die Farbe bei allen vordefinierten Blöcken setzen? Blöcke ohne Farbe werden im Picasso ganz weiss dargestellt, und sind dadurch quasi unsichtbar.

2020-01-28 15:29 UTC, manuelmeister commented on frontend/src/App.vue
> -  @import '../node_modules/typeface-roboto/index.css';
Ich nehme an du hast es auf Linux ausprobiert. Ich habe nichts gegen Roboto und finde die Schriftart gut, aber ich möchte einfach keine Schriftart einbinden. Was hast du auf Linux "Standardmässig" installiert? Noto Sans & Roboto?
Dann könnte man das noch in den Font-Family Stack hineinnehmen. Auf Windows wird Segoe UI angezeigt.

2020-01-28 16:01 UTC, manuelmeister commented on frontend/src/views/auth/Login.vue
> +  </v-content>
Finde ich auch, es ist nicht optimal, dass die eCamp, Google & Hitobito Loginbuttons nebeneinander stehen. Sie können ja unabhängig vom Benutzername usw gedrückt werden zum einloggen.

2020-01-28 16:07 UTC, manuelmeister commented on backend/module/eCampCore/data/dev/EventCategoryData.php
> +            $eventCategory->setColor('#8bc34a');
Am Schluss werde ich die Standardfarben noch optimieren auf Farbblindheit und Lesbarkeit.

2020-01-28 20:43 UTC, usu commented on frontend/src/App.vue
> -  @import '../node_modules/typeface-roboto/index.css';
Was ist der Grund, dass du keine Fonts einbinden möchtest? Wenn wir die Schriftart vorgeben, hat das den grossen Vorteil dass wir das Look & Feel viel besser kontrollieren können.

2020-01-28 21:20 UTC, carlobeltrame commented on frontend/src/App.vue
> -  @import '../node_modules/typeface-roboto/index.css';
Die Systemschriftart ist Ubuntu (https://css-tricks.com/snippets/css/system-font-stack/), aber ich dachte das hat sich vor noch nicht allzu langer Zeit geändert.

Ich würde mich aber wirklich fragen ob eine Font der richtige Ort ist um vorab Bandbreite zu sparen. Bei SPAs würde ich da eher darauf achten welche Dependencies eingebunden werden, damit kann viel mehr gespart werden wenn es dann so weit ist dass es ein Problem wird.

2020-01-28 21:29 UTC, usu reviewed
Sieht cool aus, danke vielmals fürs finale Migrieren. Die meisten Punkte sind eher als Kommentare/Anregungen zu verstehen und nicht als Change-requests fürs mergen.

2020-01-28 21:29 UTC, usu commented on frontend/src/components/camp/Basic.vue
> +    <v-skeleton-loader v-if="campDetails.loaded" type="article" />
👍 sieht cool aus

2020-01-28 21:29 UTC, usu commented on frontend/src/components/camp/Basic.vue
> +    <v-toolbar dense color="blue-grey lighten-5">
Da lohnt es sich wahrscheinlich später mal ne Komponente daraus zu erstellen, so dass alle diese Cards immer gleich aussehen. Für migration aber völlig ok für mich.

2020-01-28 21:29 UTC, usu commented on frontend/src/components/camp/Periods.vue
> +  <v-card>
Da fehlt jetzt zum Beispiel das Look & Fool der anderen Seiten. Aber kann man dann ja eben mit einer separaten Komponente lösen.

2020-01-28 21:29 UTC, usu commented on frontend/src/layouts/DefaultLayout.vue
> +    <v-bottom-navigation v-if="$vuetify.breakpoint.xs && this.$route.params.campUri" fixed grow>
👍

2020-01-28 21:29 UTC, usu commented on frontend/src/layouts/DefaultLayout.vue
> +    <v-app-bar v-if="$vuetify.breakpoint.smAndUp && !this.$route.params.campUri"
Find ich im Desktop-Modus gewöhnungsbedürftig, dass mir die komplette Top-Navigation ausgewechselt wird. Können wir das an der nächsten Sitzung nochmals ansprechen?

2020-01-28 21:29 UTC, usu commented on frontend/src/layouts/DefaultLayout.vue
> +  .ec-campselect .v-select__slot input {
Du kannst auch mit scoped styles arbeiten (https://vue-loader.vuejs.org/guide/scoped-css.html). Dann müssen die CSS-Klassen nicht zwingend einen prefix haben.

2020-01-28 21:29 UTC, usu commented on frontend/src/views/auth/RegisterDone.vue
> +  :root {
Ich glaube die Styles kannst du alle löschen, müssten obsolet sein.

2020-01-28 22:07 UTC, manuelmeister commented on frontend/src/App.vue
> -  @import '../node_modules/typeface-roboto/index.css';
Für mich ist die Geschwindigkeit am wichtigsten.
Ich finde den exakten Look & Feel in einer WebApp nicht so mega wichtig zwischen unterschiedlichen Geräten. Den meisten Leuten wird das nicht auffallen, dass die Schrift anders ist.
Besonders auf Mobile sehe ich keinen Grund eine Schriftart einzubinden, die auf langsamen 3G Netzwerk noch lange braucht zum laden. Zusätzlich rendert jedes Gerät die Schriftart etwas anders und das heisst, dass Roboto sowieso überall noch anders aussieht.

Ich werde morgen noch den ursprünglichen Fontstack von Medium aktivieren, bei dem jedes Gerät seine Systemschriftart auswählt.
Ich finde, wenn das ganze läuft, können wir immer noch über spezielle Schriftarten diskutieren, dann würde ich auch schauen, dass wir eine gute Loading Strategie haben.

2020-01-28 22:09 UTC, manuelmeister commented on frontend/src/layouts/DefaultLayout.vue
> +  .ec-campselect .v-select__slot input {
Hat eben nicht geklappt, weil das Menu auf einer anderen Ebene eingefügt wird.
Sonst war das schon mein Ziel.

2020-01-28 22:10 UTC, manuelmeister commented on frontend/src/views/auth/RegisterDone.vue
> +  :root {
Die sind vergessen gegangen.

2020-01-28 22:11 UTC, manuelmeister commented on frontend/src/components/camp/Periods.vue
> +  <v-card>
Jap, da habe ich mich noch nicht ganz entschieden.

2020-01-29 21:37 UTC, manuelmeister commented on frontend/src/App.vue
> -  @import '../node_modules/typeface-roboto/index.css';
Ich schliesse diesen Punkt. Am besten besprechen und testen wir das am nächsten Core Meeting.

2020-01-29 21:47 UTC, manuelmeister commented on frontend/src/App.vue
> -  @import '../node_modules/typeface-roboto/index.css';
Ich schliesse diesen Punkt. Am besten besprechen und testen wir das am nächsten Core Meeting. @carlobeltrame ist das okay für dich? Dann könntest du es mergen.

2020-01-30 12:11 UTC, carlobeltrame commented on frontend/src/App.vue
> -  @import '../node_modules/typeface-roboto/index.css';
Ja ist ok wenn es ein Ticket dazu gibt. Zur Info, die Fonts die du im Commit "Added Fonts for Linux users" hinzugefügt hast sind alle nicht standardmässig installiert auf Ubuntu, daher fällt es jetzt zurück auf sans-serif, was Deja Vu Sans ist (wenigstens nicht mehr Arial). Zu `ui-system` finde ich gar keine Referenz auf dem Internet, denkst du das bewirkt irgendwo etwas?

2020-01-30 12:33 UTC, merged

2020-01-30 13:42 UTC, manuelmeister commented on frontend/src/App.vue
> -  @import '../node_modules/typeface-roboto/index.css';
Danke.
Ja, es müsste `system-ui` (https://caniuse.com/#feat=mdn-css_properties_font-family_system_ui) heissen.
Sorry ich habe mich verlesen. Dann passe ich in diesem Fall noch den Fontstack an, damit Deja Vu Sans verwendet wird.

2020-02-09 12:52 UTC, usu commented on frontend/src/layouts/DefaultLayout.vue
> +  .ec-campselect .v-select__slot input {
Mit Deep-Selectors müsste es theoretisch gehen. Aber ja, hatte da auch schon meine Mühe.
https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors