Fix locale for date rendering
ecamp/ecamp3 pull request #3591
Opened 2023-06-26 05:57 UTC by manuelmeister

We want to use the swiss specific locale for the moment. If we someday want to allow other values, then I would suggest making this a setting in the profile.

2023-06-27 11:24 UTC, carlobeltrame requested changes
The same thing needs to be done here as well: https://github.com/ecamp/ecamp3/blob/devel/frontend/src/components/print/print-react/documents/campPrint/renderPdf.worker.js#L30

The web worker does not share the same dayjs object with the main thread (because you cannot share objects between the two contexts). So when starting the web worker, we have to specify the locale again for the web worker dayjs.

2023-06-27 13:44 UTC, usu approved these changes

2023-06-27 14:53 UTC, carlobeltrame approved these changes
Thanks!

2023-06-27 14:53 UTC, merged

2023-07-06 13:27 UTC, usu commented
@manuelmeister On the dev deployment, I still see some places, where American date format is being use, when language is set to English: 

Schedule Entry view:
<img width="796" alt="Screenshot 2023-07-06 at 08 24 50" src="https://github.com/ecamp/ecamp3/assets/449555/bdcf674e-cc74-43cd-8c1d-c9758a08fbfc">

Nuxt Print (consistently wrong):

<img width="675" alt="Screenshot 2023-07-06 at 08 26 03" src="https://github.com/ecamp/ecamp3/assets/449555/bb679fee-f27c-4403-9b7b-92a98417e7f8">
<img width="712" alt="Screenshot 2023-07-06 at 08 26 25" src="https://github.com/ecamp/ecamp3/assets/449555/32ce1e38-9778-44ac-adeb-f744484fc079">
<img width="712" alt="Screenshot 2023-07-06 at 08 26 39" src="https://github.com/ecamp/ecamp3/assets/449555/3c8b016a-807c-46fb-80d1-930840617d05">