Beautify routes
ecamp/ecamp3 pull request #365
Opened 2020-01-31 15:56 UTC by carlobeltrame

Fixes #345 
Depends on #357 because that PR "fixes" a backend bug that created visual problems when updating an event.

In this PR...
* Frontend routes look like `/camps/eca44930/SoLa-2020/picasso` and `/camps/eca44930/He-La-Wolfenstein/events/1a41cdbe/LA-CDs-brennen`, but `/camps/eca44930` and even `/camps/eca44930/picasso` and `/camps/eca44930/picasso/picasso` also work as one would expect
* the new frontend dependency [slugify](https://www.npmjs.com/package/slugify) is added to convert camp titles to URL-safe strings, and its use is centralized in the router
* The camp and/or event specified in the URL can be injected as props from the router, logic is also centralized there. This is done by traversing the HAL API instead of hardcoding any URI (because we can)
* The DefaultLayout with lots of v-ifs is split into two separate layouts (DefaultLayout and CampLayout)
* The API store now outputs more intelligent dummies for arrays that are still loading
* It is now possible to reload embedded collections, making the gap that was noticed in #359 smaller
* Adds convenience links to the home page to seed the database when starting the application for the first time in Docker
* General clean up of the existing frontend components

2020-02-02 12:04 UTC, pmattmann requested changes
Der Store gibt ja Loading-Proxies zurück, solange der eigentliche Inhalt noch unbekannt ist.
Da scheint es noch ein Problem zu geben. Grund habe ich aber noch nicht gefunden.

Das Problem zeigt sich bei einem Browser-Refresh bei der Anzeige eines Events.
http://localhost:8080/camps/6c1216f9/Camp1Title/events/a003ecc7/Event-LA

Wenn direkt die Event-URL abgerufen wird, kann irgendwie nicht alles sauber geladen werden.
Wenn man dahin navigiert, funktioniert es jedoch tip top...

2020-02-02 12:04 UTC, pmattmann commented on frontend/src/router.js
> +    return this.api.get().camps().items.find(camp => camp.id === route.params.campId)
Hier möchte ich gerne kurz diskutieren, ob das der richtige Weg ist.
Kurz meine Pros/Cons zu dieser Lösung:
(+) Weiterhin nur die Navigation-Properties der API genutzt (Root hat einen /camp Link)
(-) Filtern nach dem laden zwingt das Laden aller Camps. 

Daher meine Frage, ob hier nicht /camp/{route.params.campId}  geladen werden könnte.

2020-02-02 12:04 UTC, pmattmann commented on frontend/src/router.js
> +    return camp.events().items.find(event => event.id === route.params.eventId)
Gleiche Frage hier...
Wieso müssen wir alle Events laden, auch wenn wir potentiell nur an einem interessiert sind?

2020-02-02 12:27 UTC, pmattmann commented on frontend/src/router.js
> +    return camp.events().items.find(event => event.id === route.params.eventId)
Ich habe das Problem vom Refresh der Event-Seite gefunden.

Zum Zeitpunkt der Ausführung von eventFromRoute() sind die Events in der Event-Liste vom Camp noch nicht geladen. Es ist also eine Liste von Proxies.
Das Filtern mit 'find()' funktioniert auf Proxies nicht. So wird das Event nicht gefunden.

Das Problem würde sich automatisch lösen, wenn wir das laden vom Event durch 'event/{route.params.eventId}' erlauben würden.

2020-02-03 08:24 UTC, carlobeltrame commented on frontend/src/router.js
> +    return camp.events().items.find(event => event.id === route.params.eventId)
Hm guter Punkt, es gibt noch einen nicht geladenen Fall an den ich noch nicht gedacht hatte.
Wenn eine Liste von Events unter einem eigenen Endpoint geladen würde, wüssten wir noch überhaupt nichts über die enthaltenen Events. Diesen Fall habe ich in loadingArrayProxy abgedeckt.
Wenn wir aber eine Liste von Referenzen bekommen (also URI aller Elemente ist bekannt aber nichts sonst), dann tritt der beschriebene Fehler auf.
Unabhängig davon ob wir die Routen hardcoden, muss ich das noch fixen. Könnte sein dass ich eine Liste von Referenzen speziell behandeln muss.

2020-02-03 08:30 UTC, carlobeltrame commented on frontend/src/router.js
> +    return this.api.get().camps().items.find(camp => camp.id === route.params.campId)
Wir hatten ja an der Sitzung besprochen dass ich /camp/{route.params.campId} erst mal hardcoden sollte. Ich habe dann aber diese auf den ersten Blick elegante Lösung gefunden, daher mal diese implementiert.
Das Problem mit dem Laden der ganzen Camp-Liste sehe ich ein, aber für mich geht die Kernidee von HAL verloren wenn wir das hardcoden. Wenigstens wäre es jetzt nur genau im router.js wenn wir es trotzdem so machen würden.
Die richtige Lösung nach HAL wäre wohl, templated relations ([1])[https://tools.ietf.org/html/draft-kelly-json-hal-06#section-5.2]([2])[http://stateless.co/hal_specification.html] in der API mitzuliefern. Diese werden bisher im Frontend aber noch nicht unterstützt.

2020-02-03 18:20 UTC, pmattmann commented on frontend/src/router.js
> +    return this.api.get().camps().items.find(camp => camp.id === route.params.campId)
templated relations sieht spannend aus...
Lieder wird dies aktuell von zf-hal (resp. neu api-tools-hal) nicht unterstützt. Müssten wir also selber implementieren.

Siehe hier: [Link.php](https://github.com/laminas-api-tools/api-tools-hal/blob/d5b39eb58020263bdbb68060a8af9d8e2814784d/src/Link/Link.php#L401)

2020-02-03 18:28 UTC, pmattmann commented on frontend/src/router.js
> +    return this.api.get().camps().items.find(camp => camp.id === route.params.campId)
Ich möchte noch eine Idee ergänzen - damit diese nicht verloren geht.
Wenn wir uns für templated relations aussprechen sollten, wärs cool, wenn wir sowas implementieren könnten:
`
this.api.get().camps({id: 1234})
`

2020-02-04 09:48 UTC, carlobeltrame commented on frontend/src/router.js
> +    return this.api.get().camps().items.find(camp => camp.id === route.params.campId)
Genau so hätte ich es mir auch vorgestellt. Ich hardcode für den Moment mal die Routen und habe dazu Issue #369 erfasst, um das in Zukunft mal zu diskutieren und ggf. implementieren.

2020-02-06 20:50 UTC, carlobeltrame commented
Habe die diskutierten Punkte umgesetzt. Bitte erneut reviewen.

2020-02-06 23:24 UTC, pmattmann approved these changes

2020-02-09 14:19 UTC, usu reviewed
Gefällt mir. Sieht gut & clean aus! 👍 

Was ich mir noch überlegt hab: Würd es Sinn machen, die URL zu korrigieren, wenn jemand von aussen mit einer alten/falschen URL kommt.
Z.B.
User lädt http://localhost:8080/camps/2881d2da/Alter-Camp-Title

Der Titel wurde in der Zwischenzeit geändert. Router löst natürlich korrekt auf. Sollen wir dann URL umschreiben auf?
http://localhost:8080/camps/2881d2da/Neuer-Camp-Title

Nur so als Idee, keine Ahnung wie aufwändig das ist.

Der Punkt Event vs. EventInstance müssten wir noch klären.

2020-02-09 14:19 UTC, usu commented on frontend/src/components/camp/Periods.vue
> -    // force reloading of all events
Nicht glücklich, dass das jetzt wegfällt. Aber ok, diskutieren wir im Issue #359

2020-02-09 14:19 UTC, usu commented on frontend/src/components/camp/Picasso.vue
> -    // force reloading of all events
Dito wie oben

2020-02-09 14:19 UTC, usu commented on frontend/src/router.js
> +      path: '/camps/:campId/:campTitle?/events/:eventId/:eventName?',
Ich dachte wir wollten eigentlich auf die eventInstance und nicht auf das Event verlinken:

`path: '/camps/:campId/:campTitle?/events/:eventInstanceId/:eventName?',`

Ansonsten fehlt der Tageskontext für die Seitenansicht.

2020-02-09 17:26 UTC, carlobeltrame commented on frontend/src/router.js
> +      path: '/camps/:campId/:campTitle?/events/:eventId/:eventName?',
Guter Punkt, dann ändere ich aber auch Event.vue ab und benenne die Variabeln überall `eventInstance` oder `instance` statt `event`.

2020-02-09 17:28 UTC, carlobeltrame commented on frontend/src/components/camp/Periods.vue
> -    // force reloading of all events
Okay, wir könnens auch wieder reinmachen. Hat für mich nach Anti-Pattern und Gebastel ausgesehen, das vom Debugging mal noch übrig geblieben ist, darum hab ichs mal "aufgeräumt".
Mit diesem PR ist es aber ab sofort möglich, sogar embedded collections zu reloaden, falls sich in Zukunft mal jemand unüberlegt ein Beispiel an diesem event reloading nimmt. Wenn ihr das event reloading also explizit (begründet) wollt können wirs auch wieder reinmachen, und vielleicht den duplizierten Code irgendwo zentralisieren.

2020-02-09 17:32 UTC, carlobeltrame commented
@usu Zum URL korrigieren: Könnte man machen, muss aber via `router.push(some_route)` geschehen. Ich bin mir nicht ganz sicher was das für Auswirkungen hat wenn die neue Route wieder dieselbe ist. Könnte sein dass der Router alle Komponenten neu macht, alle neu mountet, oder gar nichts (was wir uns wünschen würden). Auf jeden Fall würde die Ladezeit der Seite verlängert, da wir das ganze erst machen können nachdem das Camp von der API geladen ist.
In der aktuellen Implementation hingegen stimmt die URL spätestens wieder nachdem der User irgendeinen Navigations-Link angeklickt hat.

2020-02-09 18:04 UTC, usu commented on frontend/src/router.js
> +      path: '/camps/:campId/:campTitle?/events/:eventId/:eventName?',
Yep, agree 👍

2020-02-14 11:50 UTC, carlobeltrame commented
Habe die Event-Ansicht überarbeitet mit EventInstance-ID in der Route. Dabei habe ich auch gleich die Sidebar gefixt die noch kaputt war, und eine wiederverwendbare Picasso-Komponente erstellt. Wieder bereit zum reviewen :)

2020-02-14 16:30 UTC, manuelmeister approved these changes
Cool!
Ich habe noch herausgefunden, dass es bei der Period-Ansicht jetzt keinen loading-State hat.
Habe das gelöst: https://github.com/manuelmeister/ecamp3/tree/carlobeltrame/beautify-routes-with-configurable-hydrators

2020-02-14 17:03 UTC, carlobeltrame commented
Cool, merci!

2020-02-17 18:05 UTC, merged