Feature/admin edit periods
ecamp/ecamp3 pull request #367
Opened 2020-02-02 20:37 UTC by pmattmann

Erster Entwurf für einen modalen Dialog mit einem Form

2020-02-17 18:23 UTC, pmattmann reviewed
- Component für Modal-Dialog
- Component für Period-Edit

Wenn möglich, Speicher-Code in Modal-Dialog verschieben


- Component für "Delete-Prompt"

2020-02-17 18:23 UTC, pmattmann commented on frontend/src/components/camp/Basic.vue
> +          <v-btn color="secundary" @click="cancelEditPeriod()">Close</v-btn>
typo

2020-02-25 12:43 UTC, carlobeltrame requested changes
Sieht cool aus! Ich bin mal sehr kritisch drübergegangen und habe überall meinen Senf dazugegeben. Vieles kann man auch unterschiedlich sehen oder noch darüber reden.

2020-02-25 12:43 UTC, carlobeltrame commented on backend/module/eCampCore/src/EntityService/PeriodService.php
> +        $this->getServiceUtils()->emFlush();
Weshalb ist das dazugekommen?

2020-02-25 12:43 UTC, carlobeltrame commented on frontend/src/components/dialog/DialogBase.vue
> +      this.visible = (!!id)
Man könnte visible in ein `computed` umwandeln, dann brauchts kein watch dafür.

2020-02-25 12:43 UTC, carlobeltrame commented on frontend/src/components/dialog/DialogForm.vue
> +        </v-btn>
Könnten wir das vielleicht generisch halten, mit drei Props `submitAction`, `submitLabel` und `submitColor` (mit default `success`) statt `create`, `update` und `del`? Ist dann etwas aufwändiger von aussen zu verwenden, aber dann könnte man das DialogForm auch für weitere Use Cases (z.B. Suche, Filtereinstellungen etc.) wiederverwenden. Die Logik im Form ist ja bei allen drei Fällen exakt die gleiche.

2020-02-25 12:43 UTC, carlobeltrame commented on frontend/src/components/dialog/DialogForm.vue
> +    },
Reine Geschmackssache, aber das könnte man auch so schreiben:
```js
async doCreate() {
  this.isSaving = true
  await this.create()
  this.isSaving = false
}
```

2020-02-25 12:43 UTC, carlobeltrame commented on frontend/src/components/dialog/DialogBase.vue
> +    cancel () {
Das würde ich jetzt `close` nennen, da es nicht nur im Abbruch-Fall verwendet wird

2020-02-25 12:43 UTC, carlobeltrame commented on frontend/src/components/dialog/DialogForm.vue
> +        <slot name="actions" />
Cool dass man so noch weitere Submit-Optionen einfügen kann! Ist wohl eine Design-Frage, aber sollte der primary submit button nicht eher ganz rechts sein? @manuelmeister gibts da irgendwelche Gründe für das eine oder das andere?

2020-02-25 12:43 UTC, carlobeltrame commented on frontend/src/components/dialog/DialogForm.vue
> +    <v-card>
Um die v-card herum würde ich noch ein `<v-form @submit.prevent="doSubmit">` machen, und auf dem primary submit button `type="submit"` und die `@click` dort entfernen. Dann kann man auch mit der Enter-Taste den Dialog absenden.

2020-02-25 12:43 UTC, carlobeltrame commented on frontend/src/components/dialog/DialogBase.vue
> +        this.api.get(uri)._meta.loaded.then(this.setEntityData)
`loaded` wurde vor Kurzem umbenannt in `load`. Gibt sonst einen Konsolenfehler.
```suggestion
        this.api.get(uri)._meta.load.then(this.setEntityData)
```

2020-02-25 12:43 UTC, carlobeltrame commented on frontend/src/components/dialog/CreatePeriodDialog.vue
> +    value: function (camp) {
Wenn ich auf den gleichen Dialog mehrmals öffne und jedes Mal etwas eintippe, werden meine alten Eingaben zwar weiterhin angezeigt, aber später nicht an die API gesendet. Genauso beim Edit Dialog. Vielleicht diese Logik nicht in einem Watcher ausführen (der nicht nochmals aufgerufen wird wenn ich das zweite Mal auf den gleichen Create oder Edit Button klicke), sondern stattdessen in `created` oder `mounted`.

2020-02-25 12:43 UTC, carlobeltrame commented on frontend/src/components/dialog/DialogBase.vue
> +    value: { default: null, required: true }
ESLint hätte hier gerne einen `type`. `type: Object` gibt aber Konsolen-Fehler während der Inhalt noch nicht fertig geladen ist. Vielleicht die prop auf `required: false` setzen und den angezeigten Inhalt mit einem v-if vor dem ungeladenen Fall schützen? Dann würde sogar das `visible` Flag wegfallen.
Aber: Könnte es nicht sein dass wir in Zukunft mal einen Dialog brauchen machen der nicht direkt genau einem Objekt zugewiesen wird? Z.B. ein Confirmation-Dialog oder Informations-Dialog oder so? Bin mir nicht sicher ob ich die Logik die mit `value` zu tun hat z.B. in einen CreateDialogBase verschieben würde.

2020-02-25 12:43 UTC, carlobeltrame commented on frontend/src/components/dialog/DialogBase.vue
> +        this.$emit('input', null)
Wieso ist das nötig? Und beschreibt `'input'` wirklich korrekt was hier passiert?

2020-02-25 12:43 UTC, carlobeltrame commented on frontend/src/components/camp/Basic.vue
> +                @click="() => { createPeriodCamp=camp() }">
```suggestion
                @click="createPeriodCamp=camp()">
```

2020-02-25 12:43 UTC, carlobeltrame commented on frontend/src/components/camp/Basic.vue
> +      the Period "{{ (deletePeriod || {}).description }}"
Brauchts das `|| {}` hier wirklich? Der Dialog sollte ja gar nicht angezeigt werden falls `deletePeriod === null` ist

2020-02-25 12:43 UTC, carlobeltrame commented on frontend/src/components/camp/Basic.vue
> +    <delete-entity-dialog v-model="deletePeriod">
Irgendwie etwas unbequem dass da beim edit Dialog eine URI reingeht und bei den anderen ein Objekt. Ich wäre für Vereinheitlichung. Immer eine URI hineingeben ginge zwar hier gut, aber ich könnte mir auch mal Dialoge vorstellen deren Daten nicht durch einen String ausgedrückt werden können. Immer ein Objekt reingeben ginge aber eigentlich gut soweit ich das beurteilen kann.

2020-02-25 12:43 UTC, carlobeltrame commented on frontend/src/components/dialog/DialogBase.vue
> +        this.entityUri = uri
Ich würde die URI stattdessen aus den geladenen Daten fischen, dann ist es nämlich egal ob man eine URI oder eine Entity in loadEntityData reingibt (der API store kann bereits beides). Also in `setEntityData`:
```js
this.entityUri = data._meta.self
```
Oder übersehe ich da etwas?

2020-02-25 12:43 UTC, carlobeltrame commented on frontend/src/components/camp/Basic.vue
> +                  </span>
Könnte man dasselbe so schreiben?
```html
<v-icon :left="$vuetify.breakpoint.smAndUp" size="150%">mdi-pencil</v-icon>
<span class="d-none d-sm-block">Edit</span>
```

2020-02-25 12:43 UTC, carlobeltrame commented on frontend/src/components/camp/Basic.vue
> +                  </span>
dito

2020-02-25 19:35 UTC, pmattmann commented on backend/module/eCampCore/src/EntityService/PeriodService.php
> +        $this->getServiceUtils()->emFlush();
Grund is, dass der DayService danach die ID überreicht bekommt - und die neue Periode von der DB laden können muss.

2020-02-25 20:08 UTC, pmattmann commented on frontend/src/components/dialog/DialogForm.vue
> +    },
einverstanden

2020-02-25 20:08 UTC, pmattmann commented on frontend/src/components/dialog/DialogBase.vue
> +    cancel () {
einverstanden

2020-02-25 20:39 UTC, pmattmann commented on frontend/src/components/dialog/DialogForm.vue
> +        </v-btn>
Finde die Idee mit den Properties bestechend, habe ich umgebaut

2020-02-25 20:41 UTC, pmattmann commented on frontend/src/components/dialog/DialogForm.vue
> +        <slot name="actions" />
Kann man sicher verschiedene Meinungen haben... 
Hier wird z.B. "OK" auf rechts empfohlen. Habe es auch mal angepasst - erwartete Action unten rechts.

https://uxmovement.com/buttons/why-ok-buttons-in-dialog-boxes-work-best-on-the-right/

2020-02-25 20:41 UTC, pmattmann commented on frontend/src/components/dialog/DialogForm.vue
> +    <v-card>
einverstanden

2020-02-25 20:41 UTC, pmattmann commented on frontend/src/components/dialog/DialogBase.vue
> +        this.api.get(uri)._meta.loaded.then(this.setEntityData)
einverstanden

2020-02-25 20:43 UTC, pmattmann commented on frontend/src/components/dialog/DialogBase.vue
> +        this.$emit('input', null)
$emit('input') ist das "Value-Property-Changed"

2020-02-25 20:43 UTC, pmattmann commented on frontend/src/components/camp/Basic.vue
> +                @click="() => { createPeriodCamp=camp() }">
einverstanden

2020-02-25 20:46 UTC, pmattmann commented on frontend/src/components/dialog/DialogBase.vue
> +      this.visible = (!!id)
hab ich umgebaut - funktioniert tip top

2020-02-25 20:48 UTC, pmattmann commented on frontend/src/components/dialog/CreatePeriodDialog.vue
> +    value: function (camp) {
Dieses Verhalten kann ich nicht reproduzieren

2020-02-25 20:49 UTC, pmattmann commented on frontend/src/components/dialog/DialogBase.vue
> +    value: { default: null, required: true }
Eigentlich hätte ich gern einen Typ "Any", da es von Dialog zu Dialog anders sein kann.
Habe ich so aber nicht gefunden.

2020-02-25 20:49 UTC, pmattmann commented on frontend/src/components/camp/Basic.vue
> +      the Period "{{ (deletePeriod || {}).description }}"
Bei mir ja - habe sonst Fehler in der Console, dass NULL kein Property 'description' hat

2020-02-25 20:52 UTC, pmattmann commented on frontend/src/components/camp/Basic.vue
> +    <delete-entity-dialog v-model="deletePeriod">
Hab ich nach 3 Dialogen noch nicht so ein Gefühl dafür.
Wie oben - am liebsten würd ich den Typ "Any" haben.

2020-02-25 20:54 UTC, pmattmann commented on frontend/src/components/dialog/DialogBase.vue
> +        this.entityUri = uri
Nein, das geht nicht immer.
Gerade der "CreatePeriodDialog" ist hier etwas anders. Da müssen die Daten an die URI /api/period  geschickt werden. Es gibt kein Objekt zu dieser URI

2020-02-25 21:10 UTC, carlobeltrame commented on frontend/src/components/dialog/CreatePeriodDialog.vue
> +    value: function (camp) {
![ecamp3-wrong-payload](https://user-images.githubusercontent.com/7566995/75287890-85c71700-581b-11ea-8cca-6c6c9522d1e7.gif)

2020-02-25 21:14 UTC, carlobeltrame commented on frontend/src/components/dialog/DialogBase.vue
> +    value: { default: null, required: true }
Any gibts nicht, das sagt ja gleich viel wie wenn man keinen type angibt. Wenn wir aber Object verlangen wäre dieses Problem und die Inkonsistenz mit manchmal URI, manchmal Objekt auch gleich behoben. Die einzige andere "richtige" Lösung die ich sehe wäre, die `value` Prop gar nicht im DialogBase zu definieren, sondern in den jeweilig vererbten Dialogen. Wäre aus meiner Sicht auch nicht verkehrt.

2020-02-25 21:15 UTC, carlobeltrame commented on frontend/src/components/camp/Basic.vue
> +      the Period "{{ (deletePeriod || {}).description }}"
Okay, stimmt. Sehe auch gerade keine schönere Lösung.

2020-02-25 21:20 UTC, carlobeltrame commented on frontend/src/components/dialog/DialogBase.vue
> +        this.entityUri = uri
Das ist wahr, aber im Fall von Create verwendest du `loadEntityData` gar nie.

2020-02-26 09:30 UTC, carlobeltrame commented on frontend/src/components/dialog/DialogBase.vue
> +        this.entityUri = uri
Ah, aber `setEntityData` wird bei Create trotzdem verwendet. Dann stimme ich dir zu, ist besser so wie du es bisher gemacht hast.

2020-02-29 20:20 UTC, usu requested changes
Beim Löschen von Entitäten geht die Seite bei mir in eine Endlosschlaufe von Netzwerk-Requests. Konnte aber noch nicht herausfinden wieso. Könnt ihr das reproduzieren?

2020-02-29 20:20 UTC, usu commented on frontend/src/components/dialog/CreatePeriodDialog.vue
> +    :cancel-action="close">
Könnte man "close" gerade als default definieren?

2020-02-29 20:20 UTC, usu commented on frontend/src/components/dialog/CreatePeriodDialog.vue
> +  name: 'CreatePeriodDialog',
Evt. etwas für die nächste Sitzung:
https://vuejs.org/v2/style-guide/#Order-of-words-in-component-names-strongly-recommended

Ich hätte jetzt eher "DialogPeriodCreate" und "DialogPeriodEdit" gewählt für die Reihenfolge, so dass gleiche Entitäten mit ähnlichen Inhalten nahe beieinander sind.

2020-02-29 20:20 UTC, usu commented on frontend/src/components/dialog/DialogBase.vue
> +    value: { default: null, required: true }
Ich habe einen Vorschlag gemacht, bei der die kontekt-basierten Props (period, camp, uri, etc.) von der Anzeige der Dialogs getrennt werden. Ich denke so ist die Schnittstelle zu jedem einzelnen Dialog einfacher verständlich als mit einem generischen `value` resp. `v-model`.

https://github.com/usu/ecamp3/commits/feature/admin-edit-periods

Wahrscheinlich lohnt es sich, die Commit kurz einzeln anzuschauen. Im ersten Commit habe ich hauptsächlich Komponenten aufgesplittet und ist dann schwierig die wirklichen Änderungen zu sehen, wenn man alle 3 Commit miteinander anschaut.

2020-02-29 20:27 UTC, usu commented on frontend/src/components/dialog/DialogBase.vue
> +    value: { default: null, required: true }
Pull request dazu auf fortes repo:
https://github.com/pmattmann/ecamp3/pull/4

2020-02-29 20:32 UTC, usu commented on frontend/src/components/dialog/CreatePeriodDialog.vue
> +    value: function (camp) {
Gelöst mit dieser Code-Zeile:
https://github.com/usu/ecamp3/commit/22671b98888b66b637660a812d1399ce38230f3d#diff-800b0d5cc447fc1931a4dcf7d8224773R27

Reactivity war gebrochen.

2020-03-04 15:41 UTC, carlobeltrame commented
> Beim Löschen von Entitäten geht die Seite bei mir in eine Endlosschlaufe von Netzwerk-Requests. Konnte aber noch nicht herausfinden wieso. Könnt ihr das reproduzieren?

Hängt nicht mit den Änderungen in diesem PR zusammen, ich schau mir das mal an.

2020-03-14 12:01 UTC, usu commented
Superseded by #382

2020-03-14 12:01 UTC, closed without merging