docker-compose.yml: replace mailhog with maildev
ecamp/ecamp3 pull request #3842
Opened 2023-09-25 11:41 UTC by BacLuc

That we use a supported image and have arm images available.

closes #3528

2023-09-26 03:57 UTC, usu approved these changes
Cool, thanks. Worked for me on localhost.

2023-09-29 14:54 UTC, carlobeltrame requested changes
Please also replace mailhog on the deployments: https://pr3842.ecamp3.ch/mail/

2023-09-30 15:32 UTC, manuelmeister approved these changes
Works on my machine ;)

2023-09-30 16:29 UTC, BacLuc commented
> Please also replace mailhog on the deployments: https://pr3842.ecamp3.ch/mail/

done with https://github.com/ecamp/ecamp3/pull/3842/commits/7b6559066e29d77755afafc29bb04c2b12ca2f36

2023-10-07 09:53 UTC, usu commented
> Please also replace mailhog on the deployments: https://pr3842.ecamp3.ch/mail/

@carlobeltrame Can you re-approve this, in case you're happy with the changes, such that we can merge this?

2023-10-07 10:11 UTC, carlobeltrame approved these changes

2023-10-07 10:36 UTC, merged