HttpSegemnt
ecamp/ecamp3 pull request #402
Opened 2020-03-25 14:12 UTC by pmattmann

Supported: HttpSegment
/api/camp/{id}

Not supported: HttpQuery
/api/camp/123?{sort}

2020-03-28 15:33 UTC, pmattmann commented
Supported:
/api/camp{/camp_id}
/api/camp{/camp_id}{?page_size}

Not supported: 
/api/camp{/camp_id}?sort=name_asc{&page_size}

2020-03-29 13:15 UTC, pmattmann commented
Supported:
/api/camp{/camp_id}
/api/camp{/camp_id}{?page_size}
/api/camp{/camp_id}?sort=name_asc{&page_size}

2020-03-29 13:20 UTC, pmattmann commented
Not Supported:
Default-Values für templated Links.

Daher habe ich aktuell das "Versionierung" ganz ausgeschalten.
Andernfalls würden alle Links wie folgt erscheinen:
```
http://localhost/v{/version}/api/camp{/camp_id}{?page_size}
```

2020-03-29 16:37 UTC, manuelmeister commented
Haben wir die Versionierung nicht sowieso über einen POST Parameter?

2020-03-30 17:38 UTC, usu approved these changes
Sieht gut aus für mich. Irgendwann mal ein paar Tests wär noch toll.

2020-04-01 20:17 UTC, carlobeltrame requested changes
Looks good to me, bis auf den hal-json-normalizer Workaround

2020-04-01 20:17 UTC, carlobeltrame commented on frontend/src/plugins/store/normalizeUri.js
> +
Wie besprochen hal-json-normalizer auf v3.0.1 updaten, dann kann man den Hack weglassen.

2020-04-02 18:35 UTC, pmattmann commented on frontend/src/plugins/store/normalizeUri.js
> +
done

2020-04-02 18:38 UTC, carlobeltrame approved these changes

2020-04-03 14:41 UTC, merged