Improved Login and Register Design
ecamp/ecamp3 pull request #406
Opened 2020-03-29 23:32 UTC by manuelmeister

Closes #362
(Bild wird evtl noch durch ein ruhigeres ersetzt)

2020-03-30 18:22 UTC, usu requested changes
Ich nehme an du hast die Genehmigung von Lotos, die Bilder für eCamp zu verwenden, richtig?

Das eine Bild (140801151550_LOM.jpg) hast du nirgends referenziert, oder?

2020-03-30 18:22 UTC, usu commented on frontend/src/views/auth/Login.vue
> +        <h1 class="display-1 text-center">Anmelden</h1>
Können wir alles was oberhalb des `h1` steht in eine eigene Komponente packen? Dann musst `sso-container` auch nicht mehr global definieren.

2020-03-30 18:22 UTC, usu commented on frontend/src/views/auth/Login.vue
> +    width () {
das wird gar nicht verwendet, oder?

2020-03-30 18:22 UTC, usu commented on frontend/src/views/auth/Login.vue
> +      Photo by Markus Rohner / Lotos
Ich gehe davon aus, du hast die Genehmigung von Lotos, die Bilder für eCamp zu verwenden, richtig?

2020-03-30 18:22 UTC, usu commented on frontend/src/views/auth/Login.vue
> +          <v-btn color="primary" block
Ich finde `block` eher irritierend, weil der Button im deaktivierten Modus wie ein Input-Feld aussieht.

2020-03-30 18:22 UTC, usu commented on frontend/src/scss/global.scss
> +.fill-min-height{
Geht das nicht mit der normalen `fill-height` Klasse?

2020-03-30 18:37 UTC, usu commented on frontend/src/views/auth/Login.vue
> +          v-on="on" @click="loginPbsMiData">
Das `v-on="on"` ist zuviel.

2020-03-30 18:46 UTC, manuelmeister commented on frontend/src/views/auth/Login.vue
> +          <v-btn color="primary" block
Das habe ich so gemacht, damit der Button "gleichwertig" mit den anderen zwei Buttons ist und nur zum primary wird, wenn man die Felder ausfüllt.

2020-03-30 18:47 UTC, manuelmeister commented on frontend/src/views/auth/Login.vue
> +      Photo by Markus Rohner / Lotos
Das ist ein freies PBS Medienbild.

2020-03-30 18:50 UTC, manuelmeister commented on frontend/src/scss/global.scss
> +.fill-min-height{
Nein, wenn der Inhalt grösser als die Bildschirmhöhe wird, dann hat der Inhalt ein Overflow.

2020-03-30 21:12 UTC, usu approved these changes

2020-03-31 17:23 UTC, manuelmeister commented
@carlobeltrame wie findest du?

2020-04-01 20:04 UTC, carlobeltrame requested changes
Sieht visuell echt schön aus, nice job! Ein paar kleinere Anmerkungen, ist alles Geschmackssache von hier aus.

2020-04-01 20:04 UTC, carlobeltrame commented on frontend/src/components/layout/AuthCard.vue
> +  name: 'AuthCard'
Ich finde jetzt persönlich nicht dass diese Komponente Card heissen sollte wenn der Hintergrund auch da drin ist... aber ist nur eine einmalige Sache, wäre jetzt kein Weltuntergang.

2020-04-01 20:04 UTC, carlobeltrame commented on frontend/src/plugins/vuetify.js
> +      pbs: { component: PbsLogo },
:+1:

2020-04-01 20:04 UTC, carlobeltrame commented on frontend/src/views/auth/Register.vue
> +        prefix="@"
Ich finde das @ sollte entweder auf Login- und Register-Formular oder auf keinem von beiden sein. Zudem verwendest du auf dem Register-Formular das mdi-account-outline Icon für den vollen Namen, auf dem Login-Formular aber für den Benutzernamen.

2020-04-01 20:04 UTC, carlobeltrame commented on frontend/src/views/auth/Register.vue
> +            Die Nutzungs&shy;bedingungen akzeptieren
Könnte man diesen Trennstrich nicht stattdessen mit CSS automatisch machen lassen? Ich möchte eigentlich nicht beginnen müssen, in den Übersetzungen überall in langen Wörtern `&shy;` einzusetzen.

2020-04-01 20:04 UTC, carlobeltrame commented on frontend/src/views/auth/Login.vue
> +      <v-btn color="primary" block
Ich habe wenn ich das Formular anschaue immer noch das Gefühl dass dieser Button ein Eingabefeld ist. Vielleicht könnte es helfen wenn er nicht gleich breit wäre wie die Input-Felder? Oder mit einem leichten Schatten alle Buttons von der Bildfläche abheben? Wie wird das in Material Design üblicherweise gemacht?

2020-04-01 20:04 UTC, carlobeltrame commented on frontend/src/views/auth/Login.vue
> +        <v-spacer />
Vielleicht könntest du den Trennstrich visuell stärker vom Strich unten an einem Eingabefeld mit Fokus zu unterscheiden? Bei [Qualix](https://qualix.flamberg.ch) habe ich (von [Dropbox](https://www.dropbox.com/login) abgeschaut) eine viel hellere Farbe, andere Breite, ein "oder" sowie mehr Margins oben und unten am Trennstrich. Nicht dass das wunderschön designt wäre, aber bei eCamp verwirrt es mich dass Eingabefeld und Trennstrich so ähnlich sind.

2020-04-01 22:11 UTC, manuelmeister commented on frontend/src/views/auth/Register.vue
> +        prefix="@"
Der Benutzername ist aus meiner Sicht nur für die URL / @Mentions. Für das Login würde ich lieber die E-Mail verwenden. (Dementsprechend überall mdi-email-outline)

2020-04-01 22:14 UTC, manuelmeister commented on frontend/src/views/auth/Login.vue
> +      <v-btn color="primary" block
Ich habe nun den Text im Button zentriert. Somit finde ich, unterscheidet er sich deutlich von den Inputfeldern.

2020-04-01 22:14 UTC, manuelmeister commented on frontend/src/views/auth/Login.vue
> +      <v-btn color="primary" block
Material hat da für solch spezielle Buttons keine Definition.

2020-04-02 06:59 UTC, carlobeltrame commented on frontend/src/views/auth/Login.vue
> +      <v-btn color="primary" block
Mit dem zentrierten Text und insbesondere mit dem "eCamp-Logo" gefällt es mir nun auch sehr gut, finde man erkennt so gut die Parallelen zwischen den drei Login-Buttons.

2020-04-02 07:14 UTC, carlobeltrame requested changes
Zwei weitere "Problemli" sind mir gerade noch aufgefallen:

* Das Icon wird bei mir sowohl in Titelbar als auch beim Input-Feld abgeschnitten. Wir sollten wohl irgendwann einmal von Unicode auf ein SVG-Logo umsteigen.
* Das Hintergrundbild wird auf Querformat-Geräten nicht genügend skaliert und der Credit für Lotos ragt über die Login-Card. Denke fürs Hintergrundbild sollte man `object-fit: cover`, `position: fixed` oder `position: sticky` verwenden

![Screenshot from 2020-04-02 08-59-04](https://user-images.githubusercontent.com/7566995/78220303-8cebdf80-74c1-11ea-856f-3d3860616a11.png)

2020-04-02 07:14 UTC, carlobeltrame commented on frontend/src/views/auth/Register.vue
> +        prefix="@"
Ja oder beides akzeptieren. Aber das Backend erlaubt momentan nur den Benutzernamen und darum hast du das Feld noch nicht umgeschrieben? Dann mache ich ein separates Issue dafür damit wir das auf dem Schirm behalten: #411

2020-04-02 14:14 UTC, manuelmeister commented
@carlobeltrame Funktioniert das mit dem Hintergrundbild bei dir jetzt?
Wenn ja, dann kannst du mergen.

2020-04-02 15:04 UTC, carlobeltrame requested changes
Jetzt ist es fast perfekt. Aber sowohl in Firefox als auch in Chromium sehe ich zwei verschachtelte Scrollbars die immer sichtbar sind, auch wenn es nichts zu scrollen gibt. Könntest du z.B. den `v-content__wrap` auf `overflow: hidden` und den `sso--container` auf `overflow: auto` setzen? Und dabei darauf achten dass die eingeloggten Ansichten trotzdem weiter funktionieren?

2020-04-02 15:34 UTC, carlobeltrame approved these changes
Cooles Logo übrigens!

2020-04-02 15:34 UTC, merged

2020-04-02 15:36 UTC, manuelmeister commented
Danke. Ich habe mich am Zelt Emoji von Apple orientiert und versucht ein Spatz-Zelt nachzubauen. :)