Fix ApiColorPicker racing bug
ecamp/ecamp3 pull request #4328
Opened 2023-12-26 10:16 UTC by manuelmeister

Use default autoSaveDelay to fix #4212

2023-12-26 12:54 UTC, carlobeltrame approved these changes

2023-12-26 18:20 UTC, usu requested changes
This doesn't fix the bug - it must makes it a bit harder to get the timing right in order to reproduce 😄 

https://github.com/ecamp/ecamp3/assets/449555/d68ab4e1-d462-4e69-942b-3b4c27e97499

To me this smells like a wrong handling of dirty data.
- outside value should not override local data if local data is dirty
- outside value should not trigger an API call

2023-12-26 23:58 UTC, manuelmeister commented
@usu I agree, sadly the colorpicker always emits when the input value doesn't match the exact VColorPicker color object (which is never). This would need a wrapper component to encapsulate the colorpicker.

2023-12-29 16:55 UTC, manuelmeister commented
@usu I couldn't easily fix the picker problem. I did manage to prevent an api request if the value changes from the outside. I think we could fix the dirty problem in a separate PR.

2024-01-03 14:23 UTC, manuelmeister commented
@usu I think my PR already provides a real improvement. Could you have a look again?

2024-01-08 12:56 UTC, BacLuc approved these changes
The experience is better than before.
For most users it will be enough

2024-01-08 18:16 UTC, usu approved these changes

2024-01-08 18:20 UTC, usu commented
> @usu I couldn't easily fix the picker problem. I did manage to prevent an api request if the value changes from the outside. I think we could fix the dirty problem in a separate PR.

Opened a new issue for this at https://github.com/ecamp/ecamp3/issues/4404

2024-01-08 18:27 UTC, merged