profile endpoint
ecamp/ecamp3 pull request #441
Opened 2020-05-16 14:30 UTC by pmattmann

Profile Endpoint with language

2020-05-18 20:30 UTC, usu requested changes

2020-05-18 20:30 UTC, usu commented on backend/module/eCampApi/src/eCampApi/V1/Rpc/Profile/ProfileController.php
> +    public function getAction(User $user) {
private

2020-05-18 20:30 UTC, usu commented on backend/module/eCampApi/src/eCampApi/V1/Rpc/Profile/ProfileController.php
> +    public function patchAction(User $user) {
private

2020-05-18 20:30 UTC, usu commented on backend/module/eCampApi/src/eCampApi/V1/Rpc/Profile/ProfileController.php
> +        if ($this->authenticationService->hasIdentity()) {
else throw 403

2020-06-12 18:44 UTC, manuelmeister commented on backend/module/eCampApi/src/eCampApi/V1/Rpc/Profile/ProfileController.php
>      public function indexAction() {
TODO: Description einfügen

2020-06-12 18:47 UTC, manuelmeister commented on backend/module/eCampApi/src/eCampApi/V1/Rpc/Profile/ProfileController.php
> +            'scoutname' => $user->getScoutname(),
TODO: Nickname anstatt Scoutname verwenden

2020-06-12 18:50 UTC, pmattmann commented on frontend/src/views/Profile.vue
> +      return VueI18n.availableLocales.map(function (l) {
Use Arrow-Function

2020-06-12 18:52 UTC, merged