Allow editing instance name in layout mode
ecamp/ecamp3 pull request #4560
Opened 2024-01-27 18:50 UTC by carlobeltrame

Requested by Listo. I have to say I agree with this wish: Layout mode is the correct mode in which I am building up my activity structure, and in which I am adding e.g. a Schlechtwetterprogramm which is a prime example for the usage of layout mode.

In case we decide against this, we currently have a bug: If I activate the instance name edit text field and then switch to layout mode, the text field is still visible and can be saved from within layout mode.

2024-01-28 20:26 UTC, manuelmeister commented
I'm now not sure if we want to allow instancename editing in non layout mode. I think it would be better to just limit this to the layoutmode.

2024-01-28 20:26 UTC, manuelmeister requested changes
I'm now not sure if we want to allow instancename editing in non layout mode. I think it would be better to just limit this to the layoutmode.

2024-01-31 18:11 UTC, pmattmann approved these changes

2024-01-31 21:05 UTC, manuelmeister commented
## Core Meeting Decision

- Move button to title
- Make visible when title is hovered
- Make tabable / visible on focus 
- Implement for activity title as well
- Always display instance name edit button in layoutmode

 ![Bildschirmfoto 2024-01-31 um 22 01 06](https://github.com/ecamp/ecamp3/assets/3001985/f1d83cc2-d0c0-4a1e-936d-535648cb903e)

2024-02-04 14:50 UTC, manuelmeister approved these changes
Nice!

2024-02-04 17:03 UTC, merged