Autofocus and autoselect title of new activity
ecamp/ecamp3 pull request #4826
Opened 2024-03-26 01:50 UTC by carlobeltrame

When using eCamp myself, I noticed that the activity create dialog could be faster to use if we autofocused and pre-selected the activity title in the dialog (but only when the activity in the dialog is new).

Also I removed the default title "New activity", because this name will only lead to nondescript activities. The activity title must be descriptive in order for coaches to review a picasso. Therefore, we should stop making it easier to input badly named activities. For users who write good, descriptive names for their activities, this change does not make any difference.

2024-03-26 18:26 UTC, manuelmeister requested changes
Good idea. If we remove the default text, then we should have a descriptive dialog title.

2024-03-26 18:26 UTC, manuelmeister commented on frontend/src/components/program/DialogActivityCreate.vue
> +          title: this.entityData?.title,
If you remove this text, then I think you should set it as the dialog title. Otherwise it is not entirely clear what you are working on.

2024-03-26 22:40 UTC, manuelmeister commented on frontend/src/components/program/DialogActivityCreate.vue
> +          title: this.entityData?.title,
Sorry I must have edited a existing activity. There it is missing.

2024-03-26 22:43 UTC, manuelmeister approved these changes
Noice

2024-03-30 13:30 UTC, BacLuc approved these changes

2024-03-30 13:49 UTC, merged