Picasso
ecamp/ecamp3 pull request #500
Opened 2020-07-31 15:19 UTC by manuelmeister

2020-08-04 13:16 UTC, carlobeltrame commented on frontend/src/views/camp/CampProgram.vue
> +          v-show="!listFormat"
https://www.digitalocean.com/community/tutorials/vuejs-conditional-directives#v-show
> Usually, v-show has a performance advantage if the elements are switched on and off frequently, while the v-if has the advantage when it comes to initial render time.

Warum nicht mehr `v-if`? Und falls du doch wieder `v-if` verwendest, könntest du die Änderungen in diesem File komplett reverten.

2020-08-09 16:20 UTC, manuelmeister commented
@carlobeltrame #502 habe versucht die Periode in die URL zu übernehmen, aber das prop **period** bleibt `undefined`

2020-08-11 12:56 UTC, carlobeltrame commented
Das Problem war dass in der Camp.vue Komponente die `period` nicht an die CampProgram.vue Komponente weitergegeben wurde. Ich habe es jetzt so geändert dass automatisch alle Props weitergegeben werden.
Habe auch gleich den Rest von #502 implementiert und auf deinen Branch gepusht.

2020-10-04 10:57 UTC, pmattmann requested changes, later dismissed
#519

2020-10-04 10:57 UTC, pmattmann commented on backend/module/eCampCore/src/EntityService/ScheduleEntryService.php
> +        $scheduleEntry->setPeriod($period);
Use $period->addScheduleEntry($scheduleEntry);

2020-10-04 10:57 UTC, pmattmann commented on backend/module/eCampCore/src/EntityService/ScheduleEntryService.php
> +        $scheduleEntry->setActivity($activity);
Use $activity->addScheduleEntry($scheduleEntry)

2020-10-15 20:41 UTC, manuelmeister commented
Doesn't work fully. Main focus was on activity creation. Next tasks would be to split up the picasso because of its enormous size and existing ScheduleEntry modification

2020-10-20 17:53 UTC, manuelmeister commented
### Meeting Notes
- use Dialog for ScheduleEntryPopup

2020-10-26 06:08 UTC, manuelmeister commented
@carlobeltrame the e2e test doesn't work anymore. Are you on it, or should I try to solve it?

2020-10-26 08:21 UTC, carlobeltrame commented
Looks like a temporary Travis issue to me, I had a similar one a few days ago on a different project. Locally the commands work as expected, and the "failing" command is just waiting on the containers to bind to the network interface, which can't really go wrong just because of our code.

In the meantime, when I check out your branch and try to run the containers, the composer container yields the following error:
```
ecamp3-composer           |   Problem 1
ecamp3-composer           |     - Installation request for ocramius/proxy-manager 2.9.1 -> satisfiable by ocramius/proxy-manager[2.9.1].
ecamp3-composer           |     - ocramius/proxy-manager 2.9.1 requires composer-runtime-api ^2.0.0 -> no matching package found.
ecamp3-composer           |   Problem 2
ecamp3-composer           |     - doctrine/migrations 2.2.1 requires ocramius/proxy-manager ^2.0.2 -> satisfiable by ocramius/proxy-manager[2.9.1].
ecamp3-composer           |     - doctrine/migrations 2.2.1 requires ocramius/proxy-manager ^2.0.2 -> satisfiable by ocramius/proxy-manager[2.9.1].
ecamp3-composer           |     - ocramius/proxy-manager 2.9.1 requires composer-runtime-api ^2.0.0 -> no matching package found.
ecamp3-composer           |     - Installation request for doctrine/migrations 2.2.1 -> satisfiable by doctrine/migrations[2.2.1].
ecamp3-composer           | 
ecamp3-composer           | Potential causes:
ecamp3-composer           |  - A typo in the package name
ecamp3-composer           |  - The package is not available in a stable-enough version according to your minimum-stability setting
ecamp3-composer           |    see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
ecamp3-composer           |  - It's a private package and you forgot to add a custom repository to find it
ecamp3-composer           | 
ecamp3-composer           | Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
ecamp3-composer exited with code 2
```

This indicates to me that you have updated the dependencies a bit too far, because they require composer v2, while we still have composer 1.10 defined in docker-compose.yml.

When I try to auto-fix composer.lock using `docker-compose run composer update`, I get the following errors:
```
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package laminas/laminas-dependency-plugin ^2.0 is satisfiable by laminas/laminas-dependency-plugin[2.0.0beta1, 2.0.x-dev] but these conflict with your requirements or minimum-stability.
```

laminas-dependency-plugin v2.0 is not yet stable, so composer refuses to upgrade to it. You need to downgrade, or remove it entirely (see also #555).

2020-10-26 11:02 UTC, manuelmeister commented
I think the problem lays with travis builds. The backend build seems to self-update composer.

2020-10-27 19:49 UTC, usu commented
Einen Eintrag im Picasso mit drag & drop zu verschieben geht bei mir nicht. Folgende Fehlermeldung:
`ServerException: Server-Error 400 (Unrecognized field "startTime")`

DB hab ich schon mal abgeräumt und wieder aufgebaut. Geht das bei dir?

2020-10-28 17:27 UTC, manuelmeister commented
Sollte jetzt klappen. Da war noch eine Überreste von vorher drin.

2020-10-31 07:00 UTC, usu commented
Cool, Fehler erscheint nicht mehr.

Ansonsten ist etwas schwierig zu verstehen was bereits funktionieren sollte und was nicht funktioniert weils gar noch nicht umgesetzt ist. Ich schreib mal alles auf, und dann können wir am nächsten Meeting sortieren.

### Neue Activity erstellen
- Period Offset ist für den Nutzer nicht verständlich. Nehme ich an, dass hattest du noch vor auf Startzeit zu ändern.
- Wenn ich auf Cancel klicke, bleibt der Platzhalter für die neue Aktivität bestehen. Bewusst?
- Wenn ich submitte wird der Platzhalter entfernt bevor die echte Aktivität erscheint. Kann man das zeitgleich machen?

### Aktivität bearbeiten
- Ich finde keine Möglichkeit, um zur Detailansicht der Aktivität zu gelangen
- Länge im Dialog anpassen geht nicht: Keine Fehlermeldung aber auch kein Change. Wird im Patch-Request gar nicht mitgeschickt.
- Dito mit Offset. Wird im Patch-Request gar nicht mitgeschickt.

### Drag & Drop
Mine Wunschvorstellung wär wie folgt:
- Der User sieht live, was mit seiner Aktivität passiert (Verschieben, verlängern, etc.)
- Sobald der User die Maus loslässt wird die Aktivität im Hintergrund gespeichert
- Alternativ kann man in dieser Zeit die Aktivität sperren und ein Progress-Circle anzeigen. Wenn wir aber einigermassen stabil sind, ist das nicht mal zwingend notwendig und es reicht eine kurze Rückmeldung, wenn das Speichern erfolgreich war (analog wie beim ApiWrapper für Eingabefelder).

2020-10-31 07:28 UTC, manuelmeister commented
Ja ich bin nicht zufrieden mit meinem Resultat, da klappt noch vieles nicht so wie ich es haben möchte.

Ich hatte gemerkt, dass ich noch weitere Probleme anschneide (zB Dialog Component Embedded Collection Patch, Umrechnung von PeriodOffset auf Starttime).

2020-11-01 18:06 UTC, manuelmeister commented
@usu Danke fürs Feedback. Ich war mit all deinen Punkten einverstanden und habe es jetzt noch einmal versucht und es hat geklappt. Jetzt funktioniert alles (vielleicht noch nicht ganz so schön, zb. mit dem bildschirmfüllenden Dialog, das sollte wohl eher ein `v-menu` sein, aber alles speichert und ist bedienbar.)

2020-11-02 20:36 UTC, usu commented
> @usu Danke fürs Feedback. Ich war mit all deinen Punkten einverstanden und habe es jetzt noch einmal versucht und es hat geklappt. Jetzt funktioniert fast alles (vielleicht noch nicht ganz so schön, zb. mit dem bildschirmfüllenden Dialog, das sollte wohl eher ein `v-menu` sein, aber alles speichert und ist bedienbar.)

Yeah, sehr cool 👍 
Drag & drop scheint schon mal gut zu klappen. Irgendwas geht bei mir mit den Timepickern nicht richtig, muss mir in ner ruhigen Minute mal anschauen, woran's liegt. Code schau ich dann auch mal noch an.

Ein anderer Punkte (wohl eher für "Meeting-Discuss"): Wenn man einen Entry, verschiebt ändert die Nummerierung ja bei Bedarf nach Erhalt der Server-Antwort. Die Nummern der anderen Einträge bleiben aber natürlich gleich, selbst wenn die Nummerierung nicht mehr stimmt. Könnten wir mal andiskutieren, wie wir damit umgehen...

2020-11-03 17:51 UTC, usu requested changes

2020-11-03 17:51 UTC, usu commented on frontend/src/components/dialog/DialogActivityEdit.vue
> +      return this.api.patch(this.entityUri, this.entityData).then(this.updatedSuccessful, this.onError)
Tut das bei dir? Bei mir friert der Browser hier ein. Ich glaube Axios findet's nicht so lustig, wenn du da ganze JS-Objekte (inkl. Funktionen und so) hineindrückst (=camp & embeddedCollections)

2020-11-03 17:51 UTC, usu commented on backend/module/eCampApi/config/module.config.php
> +            4 => [
Das wird Konflikte haben mit meinem PR #570 
Kann ich aber sonst bereinigen, wenn du magst

2020-11-03 17:51 UTC, usu commented on backend/module/eCampCore/src/Hydrator/ScheduleEntryHydrator.php
> -            'endTime' => Util::extractDateTime($scheduleEntry->getEndTime()),
Wollen wir die nicht drin lassen? Finde ich eigentlich schon noch user-friendly, das via API gleich zur Verfügung zu stellen.

2020-11-03 17:51 UTC, usu commented on backend/module/eCampCore/src/EntityService/ActivityService.php
> +        if (isset($data->campId)) {
Dito wegen PR #570. Kann ich flicken.

2020-11-03 17:51 UTC, usu commented on backend/module/eCampCore/src/EntityService/ActivityService.php
> +            $camp->addActivity($activity);
Ich glaube nicht, dass wir das erlauben wollen (Camp einer bestehenden Activity ändern).

2020-11-03 17:51 UTC, usu commented on backend/module/eCampLib/src/Hydrator/Util.php
> +        return $date->getTimestamp() * self::MillisecondsInASecond;
Weil in Javascript Milliseconds gängig ist?

2020-11-03 17:51 UTC, usu commented on docs/Untitled Diagram.drawio
> +<mxfile host="app.diagrams.net" modified="2020-08-25T18:33:16.964Z" agent="5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36" version="
Kann das weg?

2020-11-03 17:51 UTC, usu commented on backend/module/eCampLib/src/Service/UnattachedEntityException.php
> +<?php
Wird das verwendet?

2020-11-03 17:51 UTC, usu commented on frontend/src/plugins/scheduleEntries.js
> +function defineHelpers (scheduleEntry, timed = false) {
Nicht sicher ob der Ordner "plugins" der richtige Ort ist für die helpers. Alles andere sind ja Plugins, welche global bei Vue registriert werden

2020-11-03 17:51 UTC, usu commented on frontend/src/components/form/base/ETimePicker.vue
> +    value: { type: [Number, String], required: true },
Der EDatePicker bräuchte eine ähnliche Ergänzung. Der kann nämlich noch nicht mit Number umgehen und ist damit broken (z.B. Periode editieren).

2020-11-03 22:03 UTC, manuelmeister commented on backend/module/eCampCore/src/Hydrator/PeriodHydrator.php
> +            'end' => Util::extractTimestamp($period->getEnd()),
## Meeting Notes
Lieber ISO string da lesbarer.

2020-11-03 22:06 UTC, manuelmeister commented on backend/module/eCampLib/src/Service/UnattachedEntityException.php
> +<?php
Entfernen

2020-11-06 15:56 UTC, manuelmeister commented on backend/module/eCampCore/src/Hydrator/ScheduleEntryHydrator.php
> -            'endTime' => Util::extractDateTime($scheduleEntry->getEndTime()),
## Meeting Notes

Wird zu einem späteren Zeitpunkt geändert.

2020-11-07 09:15 UTC, manuelmeister commented
This PR is superseded by #595

2020-11-07 10:05 UTC, closed without merging