Translations
ecamp/ecamp3 pull request #516
Opened 2020-09-27 08:04 UTC by feigenmann

translations improved for en fr it and de and all swiss derivates

2020-09-30 19:15 UTC, carlobeltrame requested changes
Merci vielmal! Wie besprochen, bitte einfach noch das Format korrigieren.

2020-09-30 19:15 UTC, carlobeltrame commented on frontend/src/locales/de.json
> -    },
Diese Zeile wiederherstellen

2020-09-30 19:15 UTC, carlobeltrame commented on frontend/src/locales/de.json
> +        "server_error":{
```suggestion
        "serverError":{
```

2020-10-15 16:38 UTC, manuelmeister commented
@feigenmann meinst du, du schaffst diesen PR noch anzupassen?

2020-10-18 11:43 UTC, feigenmann commented
> meinst du, du schaffst diesen PR noch anzupasse

Ja also ich habe soweit den Code angepasst und alle Files haben gleichviele zeichen
somit kann ich jetzt einen neuen pull request starten oder?

2020-10-23 14:15 UTC, closed without merging