replace hard coded api urls with templated links
ecamp/ecamp3 pull request #5168
Opened 2024-05-11 21:55 UTC by bb1950328

fixes #977
successfully tested by verifying that all `mounted()` functions are called at least once and checking that the api calls still work by doing the corresponding action in the ui

2024-05-12 09:38 UTC, BacLuc approved these changes
Thank you very much.
Tested it locally, all dialoges still work and the href does not lead to an additonal request.

2024-05-12 14:16 UTC, manuelmeister requested changes, later dismissed
Wouldn't this make sense to move these individual mounted definitions to the `DialogBase` and provide the key, as the mounted call is identical?

2024-05-13 16:40 UTC, pmattmann approved these changes

2024-05-13 16:45 UTC, pmattmann commented
> Wouldn't this make sense to move these individual mounted definitions to the `DialogBase` and provide the key, as the mounted call is identical?

This PR exactly fulfills the issue #977 
I therefore suggest that we merge this PR as it is - and that you create a new issue with your concern.

2024-05-15 20:20 UTC, merged