Delete dialog
ecamp/ecamp3 pull request #550
Opened 2020-10-23 20:55 UTC by feigenmann

2020-10-24 09:36 UTC, carlobeltrame requested changes
Super hast dus hingebracht! Ich finde es aber nicht so gut wenn die Schattierung beim Draufzeigen auf ein Camp nicht mehr da ist, dann weiss man als User gar nicht dass man da klicken kann.

Ich habe eine andere Lösung gefunden, bei der die Schattierung bestehen bleibt und der Delete Button trotzdem geklickt werden kann ohne dass man gleich zum Camp navigiert.

2020-10-24 09:36 UTC, carlobeltrame commented on frontend/src/views/Camps.vue
> +          <v-list-item-content @click.prevent="goToCamp(camp)">
Das rückgängig machen weil sonst die Schattierung beim draufzeigen nicht mehr funktioniert

2020-10-24 09:36 UTC, carlobeltrame commented on frontend/src/views/Camps.vue
> +                <button-delete v-on="on" />
```suggestion
                <button-delete @click.prevent="on.click" />
```
`v-on="on"` ist hier dasselbe wie `@click="on.click"`. Wir müssen nur noch `.prevent` hinzufügen, damit der Klick nicht auch an den Parent (das `list-item`) weitergegeben wird.

2020-10-24 09:36 UTC, carlobeltrame commented on frontend/src/views/Camps.vue
>      },
```suggestion
```
Entfernen, da `deleteCamp` nicht mehr verwendet wird (`DialogEntityDelete` macht das bereits, jetzt wo du den einsetzt)

2020-10-24 09:36 UTC, carlobeltrame commented on frontend/src/views/Camps.vue
> +    }
Rückgängig machen, da nicht nötig wenn wir weiterhin `:to=""` verwenden

2020-10-24 09:36 UTC, carlobeltrame commented on frontend/src/views/Camps.vue
> +import router, { campRoute } from '@/router'
```suggestion
import { campRoute } from '@/router'
```
Rückgängig machen, da `router` nicht gebraucht wird wenn wir `goToCamp` nicht brauchen

2020-10-24 09:36 UTC, carlobeltrame commented on frontend/src/views/Camps.vue
> +                <li>{{ camp.title }}"</li>
```suggestion
                <li>{{ camp.title }}</li>
```
typo

2020-10-24 19:54 UTC, feigenmann commented on frontend/src/views/Camps.vue
> +          <v-list-item-content @click.prevent="goToCamp(camp)">
Ja genau das hat mich auch gestört:)

2020-10-24 19:55 UTC, feigenmann commented on frontend/src/views/Camps.vue
>      },
Ja genau.

2020-10-24 19:55 UTC, feigenmann commented
done ready  to merge.

2020-10-25 12:55 UTC, carlobeltrame approved these changes

2020-10-27 19:26 UTC, usu approved these changes

2020-11-03 18:54 UTC, merged