vscode+unittest
ecamp/ecamp3 pull request #560
Opened 2020-10-27 14:29 UTC by pmattmann

Funktioniert zusammen mit folgender Exteionsion:
https://marketplace.visualstudio.com/items?itemName=recca0120.vscode-phpunit

2020-11-01 17:28 UTC, BacLuc commented
I verfied that phpstorm and composer runner still work.

2020-11-01 17:29 UTC, BacLuc approved these changes

2020-11-03 19:50 UTC, usu requested changes

2020-11-03 19:50 UTC, usu commented on .vscode/launch.json
> +{
Wär gut, eine ähnliche config unter `backend/.vscode/launch.json` zu haben, so dass Debug auch funktioniert, wenn ich nur das backend in VS Code öffne.

2020-11-03 19:50 UTC, usu commented on .vscode/settings.json
> +    "phpunit.files": "backend/{module,content-type}/**/test/**/*Test.php",
Dito, bitte auch in `backend/.vscode/settings.json` ergänzen. 
Bei mir laufen die Tests nicht, keine Fehlermeldung oder so. Müsstest du noch irgendwas konfigurieren oder installieren?

Und fehlt nicht noch der Path für phpunit?
`"phpunit.phpunit": "backend/vendor/bin/phpunit"`

2020-11-03 19:52 UTC, manuelmeister commented
@usu setzt seine Kommentare gerade selber um :)

2020-11-03 19:53 UTC, merged