remove oauth popup
ecamp/ecamp3 pull request #563
Opened 2020-10-28 13:44 UTC by pmattmann

closes #548

2020-10-28 15:36 UTC, carlobeltrame requested changes
Super, merci!

2020-10-28 15:36 UTC, carlobeltrame commented on frontend/src/plugins/auth.js
>  async function oAuthLoginInSeparateWindow (provider) {
Wenn du noch diese Funktion umbenennst passts für mich.

2020-10-28 15:36 UTC, pmattmann commented on frontend/src/plugins/auth.js
>  async function oAuthLoginInSeparateWindow (provider) {
uuups

2020-10-28 15:47 UTC, carlobeltrame approved these changes

2020-10-31 05:20 UTC, usu approved these changes

2020-11-03 20:19 UTC, merged