display material-list, material-item
ecamp/ecamp3 pull request #645
Opened 2020-11-14 22:33 UTC by pmattmann

2020-11-15 10:10 UTC, feigenmann requested changes
static content please add $tc

2020-11-15 10:10 UTC, feigenmann commented on frontend/src/views/camp/NavigationCamp.vue
> +        <span class="sr-only-sm-and-down">Material</span>
static content please add $tc

2020-11-15 10:10 UTC, feigenmann commented on frontend/src/views/camp/Material.vue
> +  <content-card title="Material">
static content please add $tc

2020-11-16 22:07 UTC, pmattmann commented
- [x] Create/Edit/Delete Material-List
- [x] Create/Edit/Delete Material-Item

Not yet well styled.

2020-11-18 16:03 UTC, carlobeltrame requested changes, later dismissed

2020-11-18 16:03 UTC, carlobeltrame commented on backend/module/eCampCore/src/EntityService/CampCollaborationService.php
> +                        $this->createMaterialList($campCollaboration);
Did you forget to add a material list when a user creates a camp? In that case, the collaboration is created directly in `STATUS_ESTABLISHED`

2020-11-18 16:03 UTC, carlobeltrame commented on frontend/src/views/camp/Material.vue
> +      showActivityMaterial: false
Consider activating this switch by default, or even saved to `localStorage`

2020-11-18 16:03 UTC, carlobeltrame commented on frontend/src/components/dialog/DialogMaterialListForm.vue
> +    <e-text-field
Consider setting autofocus on the only text field in this dialog

2020-11-18 16:03 UTC, carlobeltrame commented on frontend/src/views/camp/Material.vue
> +      <v-expansion-panels multiple>
How about automatically opening the upcoming periods like I did with the story overview? Or just all periods that haven't started yet?

2020-11-18 16:03 UTC, carlobeltrame commented on frontend/src/components/camp/PeriodMaterialLists.vue
> +                </td>
Since you are constantly adding `v-if` and `v-else` on pieces here, how about extracting two separate components, one for scheduleEntry materials and one for period materials, and only using a single `v-if`?

2020-11-18 16:03 UTC, carlobeltrame commented on frontend/src/components/camp/CampMaterialListsItem.vue
> +Displays a single period as a list item including controls to edit and delete it.
Fix or remove copy pasted comments in all new files

2020-11-18 16:03 UTC, carlobeltrame commented on frontend/src/components/form/api/ApiWrapper.vue
> +        return this.api.get(this.uri)[this.relation]().id
Nice. We should add tests for this in #412

2020-11-18 16:03 UTC, carlobeltrame commented on frontend/src/views/camp/NavigationCamp.vue
> +        <span class="sr-only-sm-and-down">Material</span>
+1

2020-11-19 19:02 UTC, usu submitted a review, later dismissed
Ein paar allgemeine Punkte. Können von mir aus gerne je in separate Issue:
- Server-Fehler-Handling beim Erstellen von neuen Items
- Default-Materiallisten beim Erstellen eines Lagers (z.B. Einkauf)
- API-Test fertig schreiben
- General Look & Feel (Color, Edit-Field-Sizes, etc.)
- Eager-Adding --> wär hier halt schon irgendwie 🚀 

Hast du übrigens mal angeschaut, ob wir mit Data-Grids was machen wollen? Oder sind wir dann zu fest eingeschränkt?
- https://vuetifyjs.com/en/components/data-tables/
- https://www.njleonzhang.com/vue-data-tables
- https://madewithvuejs.com/blog/best-vue-js-datatables

2020-11-19 19:02 UTC, usu commented on frontend/src/components/camp/MaterialCreateItem.vue
> +        dense
vee-rules="required"

2020-11-19 19:02 UTC, usu commented on frontend/src/components/camp/MaterialCreateItem.vue
> +        dense
`vee-rules="required"`
Falls das geht mit e-select

2020-11-19 19:02 UTC, usu commented on frontend/src/components/camp/MaterialCreateItem.vue
> +    <v-col>
Copy Pase von DialogForm.vue:
```
<ValidationObserver v-if="value" v-slot="{ handleSubmit }">
<v-form @submit.prevent="handleSubmit(createMaterialItem)">
```

2020-11-19 19:02 UTC, usu commented on frontend/src/components/camp/MaterialCreateItem.vue
> +      <v-btn @click="createMaterialItem">
`<v-btn type="submit" :loading="isSaving">`

Dann geht Absenden auch mit Enter, zusammen mit dem v-form ganz oben. Und `isSaving` kann in `createMaterialItem` gesetzt/zurückgesetzt werden.

2020-11-19 19:02 UTC, usu commented on frontend/src/components/camp/MaterialCreateItem.vue
> +        :items="materialLists" />
falls `materialLists` leer ist, wird beim Öffnen des Dropdown `$vuetify.noDataText` angezeigt

2020-11-19 19:02 UTC, usu commented on frontend/src/components/camp/MaterialCreateItem.vue
> +        fieldname="quantity" />
`vee-rules="double"`
braucht ein Update von vee-validate

2020-11-19 19:02 UTC, usu commented on backend/module/eCampApi/src/eCampApi/V1/Rpc/Index/IndexController.php
> +        $data['materialItems'] = TemplatedLink::factory([
Wieso stecken die templated Links eigentlich alle auf unserem API-Root?

2020-11-19 19:02 UTC, usu commented on frontend/src/components/activity/content/Material.vue
> +              :uri="materialItem._meta.self"
`:uri="materialItem._meta.self` wär überflüssig wenn `<api-form>` verwendet wird

2020-11-19 19:02 UTC, usu commented on frontend/src/locales/en.json
> +      "name": "Materiallists"
Oder simpler einfach "Material"?

2020-11-19 19:02 UTC, usu commented on frontend/src/locales/en.json
> +      "name": "Materiallist"
Material list

2020-11-19 22:04 UTC, pmattmann commented on backend/module/eCampCore/src/EntityService/CampCollaborationService.php
> +                        $this->createMaterialList($campCollaboration);
yes

2020-11-23 18:48 UTC, carlobeltrame commented on frontend/src/views/camp/Material.vue
> +      showActivityMaterial: null
```suggestion
      showActivityMaterial: false
```
This fixes a console warning about unexpected property type null instead of boolean

2020-11-23 18:54 UTC, carlobeltrame commented on frontend/src/components/camp/CampMaterialLists.vue
> +<template>
```suggestion
<template>
```

2020-11-23 19:41 UTC, carlobeltrame commented on frontend/src/components/camp/CampMaterialListsItem.vue
> +              {{ $tc('components.camp.campMaterialListsItem.deleteWarning') }} <br>
Translation missing in the jsons

2020-11-26 17:55 UTC, pmattmann commented on frontend/src/components/camp/MaterialCreateItem.vue
> +        :items="materialLists" />
Könnte übersetzt werden... wird dann auch angezeigt...
unklar ist jedoch womit:
a) empty...
b) loading...

2020-11-29 15:07 UTC, manuelmeister commented on frontend/src/components/camp/MaterialCreateItem.vue
> +        :items="materialLists" />
Ich habe mir das auch für die Suche auf Mobile (die ich aber wieder über den Haufen geworfen habe) überlegt:
[#697 SearchMobile.vue](https://github.com/ecamp/ecamp3/pull/697/files#diff-0bcd2cd476216a2a5060fe5f6ec0350f0593bf96b8e8400afabd1afc3c779cecR36)
[#697 de.json](https://github.com/ecamp/ecamp3/pull/697/files#diff-c7dac166523f65b3b341b97acb20491b5b38e9b5cb20084e8db308b148f89944R225-R228)

2020-11-29 17:27 UTC, manuelmeister requested changes
Coole Sache 👍 

Mir fehlt zum Teil noch die Ladezustände. Im View `Material` sehe ich nicht, dass noch die Listen und/oder die Items geladen werden.

2020-11-29 17:27 UTC, manuelmeister commented on frontend/src/components/camp/MaterialListItemActivity.vue
> +        </template>
Wäre das nicht sinnvoller in einem computed property?

2020-11-29 17:27 UTC, manuelmeister commented on frontend/src/views/camp/NavigationCamp.vue
> +    <v-btn :to="{name: 'camp/material'}">
```suggestion
    <v-btn :to="campRoute(camp(), 'material')">
```
Funktioniert sonst nicht richtig

2020-11-29 17:27 UTC, manuelmeister commented on frontend/src/components/camp/PeriodMaterialLists.vue
> +      </div>
Finde ich cool gelöst. Würde aber das nicht nur beim Erstellen machen, sondern auch für das Bearbeiten. Auf Mobile würde ich nie (auch nicht im ActivityContent) ganze Tabellen bearbeitbar machen.
Ich würde ausserdem die möglichen Aktionen nicht mischen. Im Falle des ItemPeriod würde ein Bearbeitungs-Dialog erscheinen (mit Löschen-Funktion), bei ItemActivity wäre es einen Link auf den Bearbeitungsdialog des ItemActivity innerhalb der Aktivität.

![Screenshot 2020-11-29 at 18 14 19](https://user-images.githubusercontent.com/3001985/100548776-f39ee400-326e-11eb-8b90-3368fdc078cb.png)

2020-12-05 17:57 UTC, carlobeltrame commented on frontend/src/components/camp/MaterialCreateItem.vue
> +        :items="materialLists" />
Falls `materialLists` leer ist würde ich das Formular für neues Material gar nicht erst anzeigen, sondern einen Hinweislink auf die Camp Admin Seite wo man Materiallisten hinzufügen kann.

2020-12-05 18:04 UTC, carlobeltrame commented
ecamp2-User werden sicher anfangs überrascht sein über die neu getrennten Felder für Quantität und Einheit. Wenn ich dann als fauler User ins Quantity-Feld trotzdem 1kg eintippe, dann erscheint das Material Item beim Speichern in der Liste, wird aber nicht persistiert (d.h. nach F5 ists wieder weg). Auf der Konsole kommt folgender Fehler:
```
Uncaught (in promise) ServerException: Server-Error 500 (An exception occurred while executing 'INSERT INTO material_item (article, quantity, unit, id, createTime, updateTime, materialListId, periodId, activityContentId) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["Mehl", "1kg", null, "cc5ecdc0", "2020-12-05 18:01:23", "2020-12-05 18:01:23", "be1a73b1", "3daa1e4d", null]:

SQLSTATE[01000]: Warning: 1265 Data truncated for column 'quantity' at row 1)
```
Das möchte ich gerne noch in diesem PR gefixt haben. Am einfachsten wäre wohl, auf Quantity eine Frontend-Validierung zu machen. Schritt 2 wäre dann für mich, dieselbe Validierung auch im Backend einzuführen und die Validierungs-Fehler entsprechend anzuzeigen. Schritt 3 bzw. Luxusvariante wäre, dass ich als User 1kg in ein Feld eintippen kann, und der Wert dann automatisch auf 2 Felder aufgeteilt wird. Das wäre dann aber klar ein neues Issue.

2020-12-06 16:15 UTC, manuelmeister commented on backend/module/eCampCore/src/EntityService/MaterialItemService.php
Ich bin gerade an der Implementation des Themenbereichs und beim Stöbern dieses PRs ist mir aufgefallen, dass nicht validiert wird dass entweder eine Periode oder ein ActivityContent Referenz gesetzt ist. Stimmt das, oder habe ich da etwas übersehen?

2020-12-19 14:43 UTC, carlobeltrame commented on frontend/src/components/camp/MaterialCreateItem.vue
> +      {{ $t('components.camp.materialCreateItem.noMaterialListAwailable') }}
```suggestion
      {{ $tc('components.camp.materialCreateItem.noMaterialListAvailable') }}
```

2020-12-19 14:43 UTC, carlobeltrame commented on frontend/src/locales/de.json
> +        "noMaterialListAwailable": "Für dieses Lager sind noch keine Materiallisten erfasst. Du kannst diese unter 'Admin' erfassen."
```suggestion
        "noMaterialListAvailable": "Für dieses Lager sind noch keine Materiallisten erfasst. Du kannst diese unter 'Admin' erfassen."
```

2020-12-19 14:44 UTC, carlobeltrame commented on frontend/src/components/activity/content/Material.vue
> +              :uri="materialItem._meta.self"
Plus man könnte den Material-Eintrag glaube ich auch gleich mit ENTER speichern

2020-12-19 15:57 UTC, manuelmeister approved these changes, later dismissed

2020-12-20 11:59 UTC, manuelmeister commented
@pmattmann bist du fertig mit diesem PR?

2020-12-20 12:42 UTC, pmattmann commented
Im gross und ganzen JA.
Es gibt noch ein paar offene Punkte, welche wir auch als neue Issues erfassen können.
- Validation (double)
- Skeleton loaders

2020-12-20 12:55 UTC, manuelmeister approved these changes

2020-12-30 16:21 UTC, BacLuc approved these changes

2021-01-01 10:51 UTC, manuelmeister commented
## Issues to be created

- [ ] Error-Handling as described in https://github.com/ecamp/ecamp3/pull/645#issuecomment-739328696
- [ ] Use `<api-form>` instead of `:uri="materialItem._meta.self` https://github.com/ecamp/ecamp3/pull/645#discussion_r527122742
- [ ] Optimize skeleton / loading state / empty state https://github.com/ecamp/ecamp3/pull/645#pullrequestreview-540493260
- [ ] Validate MaterialItem for ref to either period or activity https://github.com/ecamp/ecamp3/pull/645#discussion_r537070152

2021-01-03 09:58 UTC, merged