fix ApiCheckbox
ecamp/ecamp3 pull request #673
Opened 2020-11-17 21:31 UTC by pmattmann

fixes #654

2020-11-17 23:26 UTC, manuelmeister approved these changes

2020-11-18 10:48 UTC, usu requested changes
#654 deklariert ein Bug in ApiCheckbox und ApiSwitch. Könntest du ApiSwitch auch gleich fixen? Oder funktioniert die bereits?

2020-11-18 10:48 UTC, usu commented on backend/module/eCampApi/src/eCampApi/V1/Rpc/Profile/ProfileController.php
> +            $user->setRole($data->isAdmin ? User::ROLE_ADMIN : User::ROLE_USER);
Kann das wieder weg?

2020-11-19 21:03 UTC, pmattmann commented on backend/module/eCampApi/src/eCampApi/V1/Rpc/Profile/ProfileController.php
> +            $user->setRole($data->isAdmin ? User::ROLE_ADMIN : User::ROLE_USER);
Das kann weg - irgendeinmal.
Damit unter /Controls die Checkbox und der Switch funktionieren, brauche ich ein Boolean-Value auf der API.
Wenn wir ein besseres Beispiel haben, ändere ich das gern.
Vorschläge?

2020-11-20 16:00 UTC, usu commented on backend/module/eCampApi/src/eCampApi/V1/Rpc/Profile/ProfileController.php
> +            $user->setRole($data->isAdmin ? User::ROLE_ADMIN : User::ROLE_USER);
Neues Issue dazu unter #685

2020-11-20 16:01 UTC, usu approved these changes

2020-11-22 11:34 UTC, carlobeltrame approved these changes

2020-11-22 11:34 UTC, merged