Removed unused packages
ecamp/ecamp3 pull request #781
Opened 2021-01-01 16:17 UTC by manuelmeister

2021-01-02 12:27 UTC, pmattmann requested changes
Bei mir bleibt der Login-Screen leer.
Ich glaube es hat mit SVG zu tun.

2021-01-03 12:34 UTC, BacLuc approved these changes

2021-01-03 12:34 UTC, BacLuc commented on backend/composer.json
> -        "doctrine/migrations": "^2.2",
das werden wir später wieder brauchen.
Aber es ist richtig, das erst hineinzuziehen, wenn wir es brauchen.

2021-01-03 13:25 UTC, pmattmann approved these changes

2021-01-03 13:25 UTC, merged