Run containers as local user
ecamp/ecamp3 pull request #821
Opened 2021-01-12 23:42 UTC by carlobeltrame

Fixes #819

Please test this on your operating system!
If you have an existing docker setup which you have run before, use the following commands (or an equivalent) to make sure the transition works smoothly:
```bash
# Remove all eCamp containers, volumes and images
docker-compose down --volumes --rmi local --remove-orphans
# Build new containers
docker-compose build
# Make sure all files currently in your project belong to your user, rather than root
sudo chown -R $USER .
# Bring up the project
docker-compose up
```
TODO:
- [ ] Test this with a clean newly cloned copy of the git repository and `docker system prune`'d docker
- [ ] Test it on Windows
- [ ] Test it on Mac OS
- [ ] Test it with the Makefile setup

2021-01-13 11:42 UTC, pmattmann commented on backend/config/autoload/doctrine.local.dev.php
> +return [
üblicherweise checken wir keine local-Files ein.

2021-01-13 11:44 UTC, pmattmann requested changes
remove doctrine.local.dev.php

2021-01-13 18:05 UTC, pmattmann approved these changes
👍  for Windows + WSL2

2021-01-16 15:01 UTC, manuelmeister approved these changes
Works on macOS. I noticed that print functionality no longer works, but it doesn't work on the devel branch nor on dev.ecamp3.ch, so it's not a problem of this PR.

2021-01-18 21:23 UTC, merged