add cli-commands for db-administration
ecamp/ecamp3 pull request #822
Opened 2021-01-12 23:47 UTC by pmattmann

Commands:
- Rebuild database schema (drop & create)
  - vendor/bin/laminas rebuild-database
- Update database schema (migration)
  - vendor/bin/laminas update-database
- Load Prod Data-Fixtures
  - vendor/bin/laminas load-data-fixture --path=module/\*/data/prod
- Load all Data-Fixtures
  - vendor/bin/laminas load-data-fixture --path=module/\*/data/\*

2021-01-19 16:52 UTC, BacLuc commented on .docker-hub/backend/docker-entrypoint.sh
> +vendor/bin/laminas load-data-fixture --path=module/*/data/*
hier würde der module/eCampCore/data/* reichen.
Die anderen Module sollten bis jetzt noch keine persistenz haben, oder?
Und müsste man sich hier nicht entscheiden, ob man dev oder prod daten möchte?

2021-01-19 16:53 UTC, BacLuc approved these changes

2021-01-20 10:39 UTC, carlobeltrame commented on .docker-hub/backend/docker-entrypoint.sh
> +vendor/bin/laminas load-data-fixture --path=module/*/data/*
Zu den Modulen habe ich den Befehl von Forte übernommen. @pmattmann was meinst du, ist es plausibel dass in Zukunft andere Module Persistenz dazubekommen und das hier dann vergessen geht? Falls nicht ändere ich das gerne ab.

Und Dev oder Prod Daten, auch ein guter Punkt, aber auf einer wirklich produktiven Produktion müsste man diesen Mechanismus dann sowieso ausschalten, sonst werden jedes Mal beim Deployen die Daten der User gespült. Ich habe noch zwei Notizen ins [Release-Projekt](https://github.com/ecamp/ecamp3/projects/2) gemacht, sodass das dann nicht vergessen geht. Zu bedenken ist, dass das Zurücksetzen aktuell fix in die Docker containers auf Docker Hub eingebacken ist, aber ich schätze das Risiko klein ein dass jemand vor unserem offiziellen Release schon diese Container verwendet und sich aus Versehen die Datenbank damit leert.

2021-01-20 12:13 UTC, pmattmann commented on .docker-hub/backend/docker-entrypoint.sh
> +vendor/bin/laminas load-data-fixture --path=module/*/data/*
Aus dem Verzeichnis ```module``` erwarte ich aktuell keine anderen Fixtures. Daher könnte man das auch fixieren...
Eher könnte es passieren, dass ein ContentType mal eigene Fixtures mit sich bring. Dann bedarf es eine zusätzliche Ziele (da anderes Verzeichnis).

2021-01-20 16:58 UTC, carlobeltrame requested changes
Ich schreibe noch Tests für die Commands. Abgesehen davon passts für mich.

2021-01-20 22:12 UTC, carlobeltrame approved these changes

2021-01-20 22:12 UTC, merged