Update used docker e2e cypress version
ecamp/ecamp3 pull request #826
Opened 2021-01-16 08:44 UTC by manuelmeister

I noticed that the continuous integration uses cypress 3.4.0. The current version is 6.2.1

2021-01-16 14:15 UTC, carlobeltrame requested changes
Wow, crazy how fast they publish major releases. I checked and we have next to no configuration yet, so none of the breaking changes affected us.

I'd like automate this update as well with renovate. This should be possible using the [regex manager](https://docs.renovatebot.com/modules/manager/regex/). Do you want to do this or should I have a stab at it?

2021-01-16 14:19 UTC, manuelmeister commented
You can do this, but I'm not sure it's the right approach. Currently we do not have a way to test cypress locally so I think we should tackle this first.

2021-01-16 14:35 UTC, carlobeltrame approved these changes
Alright, then let's discuss #829 at the next meeting instead.

By the way, you can run cypress locally the same way it is run on CI:
```
docker run -v ./frontend:/e2e -w /e2e --network host -e CYPRESS_BASE_URL=http://localhost:3000 cypress/included:6.2.1
```

2021-01-16 14:52 UTC, manuelmeister commented
Ah, so we could make a docker service in docker-compose.yml that runs cypress?

2021-01-16 15:32 UTC, carlobeltrame commented
Yes, but when running `docker-compose up`, all services are started, including the e2e tests, which is not really what we want.
There are ways around this:
* Creating a separate docker-compose-e2e.yml file which we could use with `docker-compose -f docker-compose-e2e.yml up`
* Making the e2e service exit immediately if it is started without a command line argument, and using it with `docker-compose run e2e run` (I did this for [Qualix](https://github.com/gloggi/qualix#end-to-end-tests))

2021-01-17 20:03 UTC, simfeld approved these changes

2021-01-17 20:19 UTC, merged