eCamp\AoT\FactoryBuilder
ecamp/ecamp3 pull request #915
Opened 2021-02-02 22:36 UTC by pmattmann

Create eCamp\AoT\FactoryBuilder
use different gen-folder for unittest

2021-02-03 10:29 UTC, carlobeltrame requested changes

2021-02-03 10:29 UTC, carlobeltrame commented on backend/module/eCampAoT/test/eCamp/AoT/DiGenerateAotTest.php
>          // Recreate empty folder
```suggestion
        // Remove temporary output folder
```

2021-02-03 10:29 UTC, carlobeltrame commented on backend/module/eCampAoT/src/FactoryBuilder.php
> +    public function useTempFolder() {
Könntest du diese Methode abändern, sodass man das directory von aussen wählen kann? Und dann vielleicht umbenennen auf `setOutputDirectory($directory = null)`? Fände ich schöner als einfach eine einzelne Alternative zu hardcoden.

2021-02-03 18:49 UTC, carlobeltrame approved these changes

2021-02-03 18:49 UTC, carlobeltrame commented on backend/module/eCampAoT/test/eCamp/AoT/DiGenerateAotTest.php
> +        // delete temporary output folder is it exists
```suggestion
        // delete temporary output folder if it exists
```

2021-02-03 18:49 UTC, carlobeltrame commented on backend/module/eCampAoT/test/eCamp/AoT/DiGenerateAotTest.php
> +        // check temporary folder does not exists
```suggestion
        // check temporary folder does not exist
```

2021-02-04 20:01 UTC, BacLuc approved these changes

2021-02-04 20:01 UTC, BacLuc commented on backend/module/eCampAoT/test/eCamp/AoT/DiGenerateAotTest.php
> +        // require self::SCRIPT_PATH;
das braucht es dann nicht mehr

2021-02-04 20:06 UTC, pmattmann commented on backend/module/eCampAoT/test/eCamp/AoT/DiGenerateAotTest.php
> +        // require self::SCRIPT_PATH;
Hast du einen alten Commit reviewed?

2021-02-04 22:01 UTC, merged