Refactor Backend for Activity-Layout
ecamp/ecamp3 pull request #950
Opened 2021-02-09 23:01 UTC by pmattmann

Refactoring for Activity-Layout (see #834)

- [x] Backend
- [ ] Frontent

2021-02-10 17:02 UTC, carlobeltrame requested changes
Ich habe kurz case-insensitive nach "activitycate", "activity-cate", "activity_cate", "contenttypeconf", "content-type-conf" und "content_type_conf" durch den Backend-Code gesucht. Alte Bezeichnungen kommen noch in einigen Strings vor, und (wichtiger) in Use Statements in ScheduleEntryTestData.php und Rest\CampTest.php, die ich in diesem Review nicht markieren kann.

2021-02-10 17:02 UTC, carlobeltrame commented on backend/module/eCampCore/src/Hydrator/CampHydrator.php
> +            'categories' => new EntityLinkCollection($camp->getCategories()),
Diese Umbenennung der Relation wird das Frontend kaputt machen. Wie gehen wir damit um?

2021-02-10 17:02 UTC, carlobeltrame commented on backend/module/eCampApi/config/Rest/category.config.php
>              'name' => 'short',
Wären Filter oder Validierungen nötig / sinnvoll für die neuen Felder?

2021-02-10 17:02 UTC, carlobeltrame commented on backend/module/eCampCore/src/Acl/AclFactory.php
> +                CategoryContentTemplate::class,
Weshalb müssen die Templates und ContentTypes auch für nicht eingeloggte User zugänglich sein? (Ich weiss das war vorher schon so)

2021-02-10 17:02 UTC, carlobeltrame commented on backend/module/eCampCore/src/Entity/ActivityContent.php
> +    private ?string $position = null;
Konntest du verifizieren dass einfache Zahlen auch als JSON gespeichert werden können?

2021-02-10 17:02 UTC, carlobeltrame commented on backend/module/eCampCore/src/Entity/ActivityContent.php
> +        $this->children->removeElement($activityContent);
`removeElement` schlägt glaube ich nicht fehl falls das Element nicht gefunden wird. Müssten wir in solche Methoden einen Safeguard einbauen der auf Plausibilität checkt, bevor `$activityContent->setParent(null)` ausgeführt wird?

2021-02-10 17:02 UTC, carlobeltrame commented on backend/module/eCampCore/src/Entity/CategoryContentType.php
> + * @ORM\Entity
Bräuchte es hier und in der parallelen Template-Klasse einen unique Index auf (category_id, content_type_id)? Bei einer "normalen" Kreuztabelle wäre es ja auch ein composite primary Key.

2021-02-10 17:02 UTC, carlobeltrame commented on backend/module/eCampCore/src/EntityService/ActivityService.php
> +            $this->activityContentService->create((object) [
Hier müsstest du glaube ich noch die initialen Inhalte sowie parent, position, etc. aus dem CategoryContent übernehmen.
Ausserdem würde ich diese Methode sehr ähnlich implementieren und ev. sogar möglichst ähnlich benennen wie `CategoryServie#createFromTemplate`, da die beiden Methoden inhaltlich praktisch dasselbe machen. Konkret würde ich das Erstellen der ActivityContents ganz dem ActivityContentService überlassen.

2021-02-10 17:02 UTC, carlobeltrame commented on backend/module/eCampCore/src/EntityService/CategoryContentService.php
> +        $categoryContent->setCategoryContentTemplateId($template->getId());
Hier müsstest du glaube ich noch die Inhalte sowie parent, position, etc. aus dem CategoryContentTemplate übernehmen.

2021-02-10 17:02 UTC, carlobeltrame commented on backend/module/eCampCore/src/Hydrator/CategoryContentHydrator.php
> +
Die eigentlichen Inhalte müssten auch noch mitgeliefert werden oder? Sonst kann man die Category nicht richtig bearbeiten.

2021-02-10 17:02 UTC, carlobeltrame commented on backend/module/eCampCore/src/Hydrator/CategoryContentHydrator.php
> +        }
... und die Inhalte müssten auch wieder schreibbar sein via API.

2021-02-10 17:02 UTC, carlobeltrame commented on backend/module/eCampCore/test/Data/CategoryContentTemplateTestData.php
> +        $categoryContentTemplate->setContentType($contentType);
Etwas wirklicher Inhalt wäre praktisch, aber nicht unbedingt nötig

2021-02-10 17:02 UTC, carlobeltrame commented on backend/module/eCampCore/test/Entity/ActivityContentTest.php
> +        $this->assertEquals($camp, $activityContent->getCamp());
Die Zeile die den ContentType testet würde ich trotzdem gerne behalten

2021-02-10 17:02 UTC, carlobeltrame commented on backend/module/eCampCore/test/Hydrator/CategoryHydratorTest.php
> +//        $this->assertEquals($camp, $data['camp']);
Kann das weg?

2021-02-10 17:02 UTC, carlobeltrame commented on backend/module/eCampCore/test/Entity/CampTemplateTest.php
>      public function testActivityCategoryTemplate() {
```suggestion
    public function testCategoryTemplate() {
```

2021-02-10 17:02 UTC, carlobeltrame commented on backend/module/eCampCore/src/EntityService/CategoryContentTypeTemplateService.php
> +        $categoryTemplate = $this->findRelatedEntity(ActivityCategoryTemplate::class, $data, 'categoryTemplateId');
```suggestion
        $categoryTemplate = $this->findRelatedEntity(CategoryTemplate::class, $data, 'categoryTemplateId');
```

2021-02-10 17:02 UTC, carlobeltrame commented on backend/module/eCampCore/src/Hydrator/CampHydrator.php
>              'activityCategories' => Util::Collection(function (Camp $c) {
```suggestion
            'categories' => Util::Collection(function (Camp $c) {
```

2021-02-10 17:02 UTC, carlobeltrame commented on backend/module/eCampCore/test/Data/CategoryTemplateTestData.php
> +    public static $TEMPLATE1 = ActivityCategoryTemplate::class.':Template1';
Hier wird noch die alte Namensgebung verwendet

2021-02-10 17:02 UTC, carlobeltrame commented on backend/module/eCampCore/test/Entity/CampTest.php
>      public function testActivityCategory() {
```suggestion
    public function testCategory() {
```

2021-02-10 17:02 UTC, carlobeltrame commented on backend/module/eCampCore/src/EntityService/CategoryContentTypeService.php
> +        return $contentTypeConfig;
```suggestion
        /** @var CategoryContentType $categoryContentType */
        $categoryContentType = $this->create((object) [
            'categoryId' => $category->getId(),
            'contentTypeId' => $template->getContentType()->getId(),
        ]);
        $categoryContentType->setCategoryContentTypeTemplateId($template->getId());

        return $categoryContentType;
```

2021-02-10 17:26 UTC, pmattmann commented on backend/module/eCampCore/test/Entity/ActivityContentTest.php
> +        $this->assertEquals($camp, $activityContent->getCamp());
war doppelt; siehe zwei Zeilen weiter oben.

2021-02-10 17:29 UTC, pmattmann commented on backend/module/eCampCore/src/Hydrator/CampHydrator.php
> +            'categories' => new EntityLinkCollection($camp->getCategories()),
Ich schlage vor; Frontent anpassen;
Ist auf der Checkliste der zweite Punkt.

2021-02-10 17:30 UTC, pmattmann commented on backend/module/eCampCore/src/Acl/AclFactory.php
> +                CategoryContentTemplate::class,
Sind unkritische Stammdaten; Check kann meiner Meinung nach gespart werden.

2021-02-10 17:42 UTC, carlobeltrame commented on backend/module/eCampCore/src/Hydrator/CampHydrator.php
> +            'categories' => new EntityLinkCollection($camp->getCategories()),
Guter plan, aber machst du das in dem fall noch in diesem PR?

2021-02-12 20:49 UTC, pmattmann commented on backend/module/eCampCore/src/Hydrator/CampHydrator.php
> +            'categories' => new EntityLinkCollection($camp->getCategories()),
Jup

2021-02-12 21:11 UTC, pmattmann commented on backend/module/eCampApi/config/Rest/category.config.php
>              'name' => 'short',
Ja - siehe #827, mach ich dann mit den ConfigFactories

2021-02-14 13:46 UTC, BacLuc commented
Bei mir scheinen die ContentTypes
- eCampSingleText
- eCampStoryBoard
nicht zu funktionieren.
eCampMaterial und eCampMultiselect funktionieren.

Liegt das an meinem Setup oder passiert das bei dir auch?
![image](https://user-images.githubusercontent.com/1506818/107878495-6d8c5400-6ed3-11eb-82bc-e0a89ec71c82.png)

2021-02-14 14:38 UTC, pmattmann commented
> Bei mir scheinen die ContentTypes
> 
> * eCampSingleText
> * eCampStoryBoard
>   nicht zu funktionieren.
>   eCampMaterial und eCampMultiselect funktionieren.

Das hatte ich auch - sollte aber korrigiert sein.
In [af6839f5](https://github.com/ecamp/ecamp3/pull/950/commits/af6839f593db48aba7d146e688a58aacf398e055)

2021-02-16 19:18 UTC, carlobeltrame requested changes
Sehr cool, wir sind auf der Zielgeraden.

2021-02-16 19:18 UTC, carlobeltrame commented on backend/module/eCampCore/src/EntityService/ActivityContentService.php
> +            $childActivityContent->setParent($activityContent);
Gibts einen Grund warum du hier und in der parallelen Template-Klasse direkt nur den Parent setzt, statt wie bei allen anderen 1:n Beziehungen das Child beim Parent einzufügen? `$activityContent->addChild($childActivityContent)`

2021-02-16 19:18 UTC, carlobeltrame commented on backend/module/eCampCore/src/Hydrator/CategoryContentHydrator.php
> +            'position' => $categoryContent->getPosition(),
Der EntityLink `parent` fehlt noch, und müsste auch schreibbar sein (oder?)

2021-02-16 19:18 UTC, carlobeltrame commented on backend/module/eCampLib/src/InputFilter/HtmlPurify.php
> +    private ?HTMLPurifier $htmlPurifier = null;
Wie wäre es wenn du stattdessen den HTMLPurifier im Konstruktor dieses Filters erstellst? Ist der so teuer zu erstellen und wird der Filter jemals erstellt ohne ihn zu verwenden dass sich das sonst lohnt mit lazy instantiation?

2021-02-16 19:18 UTC, carlobeltrame commented on frontend/src/components/camp/CampCategories.vue
> +        {{ $tc('components.camp.CampCategories.title') }}
Übersetzungsschlüssel-Segmente sollen mit Kleinbuchstaben beginnen: https://github.com/ecamp/ecamp3/wiki/Localization-and-translations#rules-for-working-with-translations, basiert auf der Konvention von Vue i18n.

2021-02-17 17:00 UTC, pmattmann commented on backend/module/eCampLib/src/InputFilter/HtmlPurify.php
> +    private ?HTMLPurifier $htmlPurifier = null;
Der Filter wird auch erstellt, wenn das Feld nicht geändert wird (PATCH).
Da ich nicht weiss, wie teuer der Filter ist (externe Component), habe ich das so gewählt.

2021-02-17 17:06 UTC, pmattmann commented on backend/module/eCampCore/src/EntityService/ActivityContentService.php
> +            $childActivityContent->setParent($activityContent);
nop... wird korrigiert

2021-02-17 17:06 UTC, pmattmann commented on backend/module/eCampCore/src/Hydrator/CategoryContentHydrator.php
> +            'position' => $categoryContent->getPosition(),
Link hinzugefügt;
Patch wird auf dem Service implementiert.

2021-02-17 20:16 UTC, carlobeltrame commented on backend/module/eCampCore/src/EntityService/ActivityContentService.php
> +            $childActivityContent->setParent($activityContent);
Merci. Dasselbe hätte ich noch gerne im CategoryContentService ;)

2021-02-17 20:28 UTC, carlobeltrame commented on backend/module/eCampCore/src/Hydrator/CategoryContentHydrator.php
> +            'position' => $categoryContent->getPosition(),
Derselbe Link fehlt mir noch auf dem ActivityContentHydrator, und das PATCH fehlt mir noch auf dem CategoryContentService.

2021-02-17 20:30 UTC, pmattmann commented on backend/module/eCampCore/src/EntityService/ActivityContentService.php
> +            $childActivityContent->setParent($activityContent);
ui... unbedingt!

2021-02-17 20:31 UTC, carlobeltrame commented
Im Frontend scheint auf den ersten Blick beim Durchklicken alles zu funktionieren. Damit #834 wirklich geschlossen werden kann fehlt mir aber noch der Umbau mit dem ["Struktur ändern" Button](https://github.com/ecamp/ecamp3/issues/834#issuecomment-770247864). Das kann man aber gerne noch separat von diesem Refactoring angehen.

2021-02-17 20:39 UTC, carlobeltrame commented on backend/module/eCampCore/src/Hydrator/CategoryContentHydrator.php
> +
Das ist weiterhin offen. Im ActivityContentHydrator#extract hast du Logik die die Strategy nach den Inhalten befragt. Dasselbe brauchts im CategoryContentHydrator.

2021-02-17 20:42 UTC, pmattmann commented
> Im Frontend scheint auf den ersten Blick beim Durchklicken alles zu funktionieren. Damit #834 wirklich geschlossen werden kann fehlt mir aber noch der Umbau mit dem ["Struktur ändern" Button](https://github.com/ecamp/ecamp3/issues/834#issuecomment-770247864). Das kann man aber gerne noch separat von diesem Refactoring angehen.

Möchte ich unbedingt trennen. Neue Funktionalität wird bestimmt auch Diskussionen geben.

2021-02-23 20:30 UTC, carlobeltrame approved these changes

2021-02-23 20:30 UTC, BacLuc approved these changes

2021-02-23 20:37 UTC, merged